### ISSUE TITLE
unexpected crash

### ISSUE THREAD

**Issue by GuardianDragonlord** [MaFi-Games/Captain-of-Industry-issues#1099] opened 2023-06-12 05:44 UTC
### Issue description

Simply letting things run as is, and operations seem to be running smoothly

### Reproduction steps

Not doing much of anything, just looking around, checking on all my buildings and seeing what was being run, and then it crashed.

### Game version and build number

v0.5.1B (B206)

### Operating system

Windows

### Attachments

[23-06-11_22-12-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11718321/23-06-11_22-12-autosave.zip)

**Comment by MaFi-Games** [comment] 2023-06-12 21:07
Can you please provide us with logs? 
Game logs at: %USERPROFILE%/AppData/Roaming/Captain of Industry.
Also include Unity logs from %USERPROFILE%/AppData/LocalLow/Mafi Games/Captain of Industry/ 
and crash reports from %USERPROFILE%/AppData/Local/Temp/Mafi Games/Captain of Industry/Crashes (zipped).

**Comment by GuardianDragonlord** [comment] 2023-06-12 22:01
both log files with the same are included in the zip file that I posted earlier it doesn't say it on the zip because it just goes with the first one. so that's why you just see the save file being named as the one in the zip  [Crashes.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11728655/Crashes.zip)

**Comment by GuardianDragonlord** [comment] 2023-06-13 22:49
the game unexpectedly crash out of nowhere while I was away from the computer 

[23-06-13_13-54-57_7436.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11740023/23-06-13_13-54-57_7436.log)
[Player.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11740024/Player.log)
[23-06-13_14-41-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11740026/23-06-13_14-41-autosave.zip)

**Comment by MaFi-Games** [comment] 2023-08-06 18:28
Duplicate of #1067

**Closed by MaFi-Games** 2023-08-06 18:28 UTC
Labels: need logs
