### ISSUE TITLE
Cargo ships travel through terrain filled in ocean.

### ISSUE THREAD

**Issue by zytukin** [MaFi-Games/Captain-of-Industry-issues#111] opened 2022-01-12 12:48 UTC
**Describe the issue**
Dump gravel, dirt, etc in the ocean.  Cargo ship pathing wont adjust for the change and the ships will travel though the land.

**To Reproduce**
Dump gravel, dirt, etc in the ocean.
Watch as cargo ships travel through it.

**Expected behavior**
Cargo ship pathing should adjust to go around terrain.  But something would need to be done to prevent players from filling in around depots and locking the ships in a small pond such as allowing players to dig out at land into the ocean.

**Attachments**
![20220112074018_1](https://user-images.githubusercontent.com/34819700/149142860-93589147-8396-41af-a0ed-4f04e56172d8.jpg)

**Comment by thetaphi** [comment] 2022-01-13 04:18
Dupe of #99

**Comment by MaFi-Games** [comment] 2022-04-07 04:38
Thanks for the report, this is now fixed and will be part of the Early Access build released in May.

**Closed by MaFi-Games** 2022-04-07 04:38 UTC
