### ISSUE TITLE
Dumping Jobs Not Respecting Export Priority Setting On Storage

### ISSUE THREAD

**Issue by RL1180** [MaFi-Games/Captain-of-Industry-issues#743] opened 2022-08-24 00:24 UTC
### Issue description

Dumping jobs do not seem to respect the priority number assigned to the storage the items are being exported from.

For example, I have several mines that have storage buildings nearby for the mining trucks to store excess rock and dirt.  The storage assigned to the mine then feeds into another storage which is set to export, with a priority between 12 and 15 (depending on the mine).  A large percentage of my trucks are exporting and dumping from these low-priority storage buildings, even when there are many other jobs available with higher priorities going unfilled.

It appears that dumping jobs have an implicit priority of 9 or 10, regardless of the priority set to storage being exported from.

### Expected behavior

I would have expected storages with export priorities of 15 would be the last jobs to be filled, only when there are no other higher priority jobs available on the island.

### Reproduction steps

1) Make sure there are plenty of non-dumping jobs available with priority 10 or 11 (enough to require all trucks to be busy doing them).
2) Fill a storage with rock or dirt.
3) Set export on rock/dirt storage, and set it to export priority 15
4) Observe that trucks will start emptying that storage, even though higher priority jobs are available.

### Game version

v0.4.10

### Attachments

[Dumping Priority Issue.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9411251/Dumping.Priority.Issue.zip)

**Comment by MaFi-Games** [comment] 2022-11-26 21:50
Duplicate of #398

**Closed by MaFi-Games** 2022-11-26 21:50 UTC
Labels: logistics, needs investigation
