### ISSUE TITLE
Sorter slowing down tier 3 belt

### ISSUE THREAD

**Issue by loneguardian** [MaFi-Games/Captain-of-Industry-issues#459] opened 2022-06-30 17:42 UTC
**Describe the issue**
I found a sorter causing bottleneck on my tier 3 U-shaped conveyer belt. Throughput seems to be halved after going through the sorter.

**Expected behavior**
Sorter should not bottleneck the tier 3 belt when there is no backing up at both output ports.

**To Reproduce**
1. Load attached save
2. The problem can be seen at the sorter array of loose storage (with tier 3 belts) next to the farms at the elevated area.

**Additional context**
Version 0.4.6
I have tried rebuilding the sorter and attaching one segment of tier 3 belt at the filter output (instead of connecting directly), the problem remains.

**Attachments**
Save file:
[issue report.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9022123/issue.report.zip)

Video in discord
https://discord.com/channels/803508556325584926/883590993063051275/992027183960829952

Similar issue has been reported by Paa#8247 at Discord, with a video in the  #message
https://discord.com/channels/803508556325584926/883590993063051275/991979319914135592

**Comment by dgzeij** [comment] 2022-07-26 21:25
Confirmed in my own save.

Would think sorters and balancers had unlimited speed internally.

I had to use contraptions like this to not clog up everything behind it:
![20220726232025_1](https://user-images.githubusercontent.com/85814950/181114700-f3f5b844-c773-41b5-9dae-74a7bebc7440.jpg)

[save_22-07-26_23-20-41 U-shape sorter is not unlimited speed.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9193426/save_22-07-26_23-20-41.U-shape.sorter.is.not.unlimited.speed.zip)

**Comment by dgzeij** [comment] 2022-07-28 17:17
Or maybe not have unlimited internal speed, since it can then be abused with 1 belt -> 1 sorter -> repeat. Maybe copy belt/pipe speed on incoming speed and use it internally in the sorter.

**Comment by MaFi-Games** [comment] 2022-11-24 15:23
Thanks for report, this was fixed in v0.4.9

**Closed by MaFi-Games** 2022-11-24 15:23 UTC
