### ISSUE TITLE
Vehicles ignore request to empty container

### ISSUE THREAD

**Issue by Magalhao** [MaFi-Games/Captain-of-Industry-issues#691] opened 2022-08-11 14:28 UTC
### Issue description

Set up first container importing to second one. Set first one to keep emty. Assign vehicles to first one. Container will be full and no vehicle will be removing cargo. It can fixed by setting second one to reguest. Then vehicles will start moving. 

### Expected behavior

Vehicles should not ignore request to empty container, since there is linked one to be filled.

### Game version

v0.4.9

### Attachments

![20220811094303_1](https://user-images.githubusercontent.com/5153243/184156838-5b137dae-497f-4431-8833-ffce078e5324.jpg)

**Comment by zuff-coi** [comment] 2022-08-12 14:16
I'll need to see your save file for me to determine the cause of this issue, could you attach it?

You'll find your saved games in "Documents\Captain of Industry\Saves"

**Comment by MaFi-Games** [comment] 2022-11-24 17:34
Closing as not enough information available.

**Closed by MaFi-Games** 2022-11-24 17:34 UTC
Labels: need save file or exact repro steps, triage
