### ISSUE TITLE
Use Assigned trucks first, before checking global pool of trucks.

### ISSUE THREAD

**Issue by MrJoshua023** [MaFi-Games/Captain-of-Industry-issues#421] opened 2022-06-24 00:12 UTC
**Describe the issue**
Bad Behavior:  If you have vehicles assigned to a storage and idling.  (but not restricted to only assigned).  The game can still grab regular trucks first for related tasks.  Feel like assigned trucks should go first, if they are idle. 

This also adds to the illusion that "its not working" when in fact another truck somewhere else is making its way.

**Expected behavior**
Assigned trucks should be assigned the task first.  If they are busy, then use the global truck pool.

**Additional context**
 - Game version: 0.4.5b

![image](https://user-images.githubusercontent.com/62954862/175435407-5e5ae45c-b71a-4447-8bc0-219c7be36885.png)

**Comment by utdrmac** [comment] 2022-06-24 01:37
Duplicate of #406. Please look for existing issues like yours before posting.

**Comment by MaFi-Games** [comment] 2022-06-27 17:56
Duplicate of #406

**Closed by MaFi-Games** 2022-06-27 17:56 UTC
