### ISSUE TITLE
Has place to dump but wont.

### ISSUE THREAD

**Issue by woodzykiler** [MaFi-Games/Captain-of-Industry-issues#1097] opened 2023-06-12 01:10 UTC
### Issue description

Trusks are NOT assigned to anything besides the tower its working from, has coal will NOT dump coal into storage.
Storage can be reached. this is not all the time, but happens at random

See image and save file

Windows 11, M.2, SSD, SSD, HDD, HDD (Total 11.7TB), 63.8GB DDR4 Ram, Ryzen 7 5700G With Graphics, Radeon RX 6600.

Caption requested the files

### Reproduction steps

Have a LOT going on/

Its a random event

### Game version and build number

V1 0.5.1b(206) Seed: 0g27ld7905la

### Operating system

Windows

### Attachments

[BED.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11716440/BED.zip)
![image2222](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/2906639/5111b6cf-b100-41fc-846c-6bbd8aabb80f)

**Comment by MaFi-Games** [comment] 2023-06-12 21:23
I let this run for a while and let the factory produce more stuff but couldn't reproduce the issue so far.

**Comment by MaFi-Games** [comment] 2023-06-20 19:12
Closing as there is not enough information. Feel free to file a new bug if you have more info.

**Closed by MaFi-Games** 2023-06-20 19:12 UTC
Labels: could not reproduce
