### ISSUE TITLE
Trucks pathfinding stuttering

### ISSUE THREAD

**Issue by McRib33** [MaFi-Games/Captain-of-Industry-issues#474] opened 2022-07-01 18:19 UTC
Hi Marek and Filip,

this bug we had in steaming session already and now i have also a save files for it (im pretty sure it is on discord already reported but not here)
the all trucks move for some seconds than hold and than move again without a good reason. (crash of the AI Pathfinding maybe).

**Expected behavior**
Trucks run smoothly. 

**To Reproduce**

Load the save files and watch the trucks. 

**Additional context**
Version 0.4.6

**Attachments**
[22-07-01_18-41-58_6195-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9030816/22-07-01_18-41-58_6195-autosave.zip)

**Comment by zuff-coi** [comment] 2022-07-12 16:59
Duplicate of #364

**Closed by zuff-coi** 2022-07-12 16:59 UTC

**Comment by zuff-coi** [comment] 2022-07-29 14:51
We [released an update on the experimental branch](https://steamcommunity.com/games/1594320/announcements/detail/4972554042131344663) which has fixes aimed at this issue. If you could please try it out and let us know if your issue is resolved that would be great!
