### ISSUE TITLE
Maintenance statistics are not accurate

### ISSUE THREAD

**Issue by ParanoikCZE** [MaFi-Games/Captain-of-Industry-issues#475] opened 2022-07-01 23:06 UTC
**Describe the issue**
The maintenance chart is displaying invalid values.
![obrazek](https://user-images.githubusercontent.com/19796452/176976021-fcedc587-aa5d-423c-aa07-1f5f969e62aa.png)

**Expected behaviour**
Real data with realistic production are displayed.

**To Reproduce**
1. Load attached save '...'
2. Open statistics on the maintenance tab
3. there is a 1.4M peak in one year that is absolutely insane and not realistic with only one M2 depot. Also while I'm on only one M2 depot since the year 508 and since then M2 supply looks more realistic. The same issue then happens for M3 which is much higher than M1, while only like 1/8 of M1 is required. So looks like M1 works fine, but M2 and M3 stats are broken if there is more than one depot.

**Additional context**
 - Game version: 0.4.6 but was observing this since 0.4.1 when I first noticed it.

**Attachments**
[22-07-01_01-22-23_2209-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9031953/22-07-01_01-22-23_2209-autosave.zip)

**Comment by MaFi-Games** [comment] 2022-08-13 17:26
Duplicate of #687

**Closed** 2022-08-13 17:26 UTC
