### ISSUE TITLE
Conveyors Duplicating Items at Junction Between Types

### ISSUE THREAD

**Issue by DustinSands** [MaFi-Games/Captain-of-Industry-issues#232] opened 2022-06-06 14:48 UTC
**Describe the issue**
Items flowing between sections of conveyor belt become duplicated (4 steel becomes 8 steel). 

**Expected behavior**
The number of items is preserved between belts.  

**To Reproduce**
1. Load attached save
2. Scroll down slightly and watch exit of Cooled Caster building (screenshot of location attached)
3. Unpause and observe every 4 resources become 8 as it travels along the belt 

**Additional context**
 - Game version: 0.4.1e
For me, this happened specifically at the junction of conveyor II to conveyor I.  I had deleted a section of belt, rebuilt it dragging from the building, and observed this behavior.  

**Attachments**
![image](https://user-images.githubusercontent.com/37489233/172184442-73513d55-d8dd-4beb-a098-58e82f758f6a.png)

[22-06-06_01-23-11_9458-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8845248/22-06-06_01-23-11_9458-autosave.zip)

**Comment by MaFi-Games** [comment] 2022-06-14 14:08
This is because we stack producs on top of each other on tier II belts, but we don't render that. This will change soon

**Comment by MaFi-Games** [comment] 2022-11-25 14:42
Duplicate of #531

**Closed by MaFi-Games** 2022-11-25 14:42 UTC
Labels: bad behavior
