### ISSUE TITLE
Mining behavior: excavator ignores available trucks

### ISSUE THREAD

**Issue by super-aardvark** [MaFi-Games/Captain-of-Industry-issues#637] opened 2022-07-29 08:23 UTC
### Issue description

I have a mining site with two excavators and several trucks.  In the screenshot, you can see three of those trucks, each partially full of iron ore.  One truck is being loaded by the other excavator.  The highlighted excavator has 2 iron ore in its bucket -- there's more than enough room in each truck for that.  However, the excavator isn't doing anything.  It's waiting for a different specific truck to return.  (Save file attached).  Once it does, it dumps its 2 iron ore into it.  At that point, there are **four** trucks with iron ore in them, three of which have fewer than 5 ore each, for **two** excavators.

### Expected behavior

Excavators should make efficient use of the available trucks by dumping iron ore into an idle truck that already has iron ore in it, rather than attempting to fill each truck with as little iron ore as possible.

### Game version

v0.4.8

### Attachments

![image](https://user-images.githubusercontent.com/3050938/181716304-31e695c6-571e-49ec-93e2-891a3530a172.png)
[mining-behavior.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9218117/mining-behavior.zip)

**Comment by zuff-coi** [comment] 2022-07-29 17:49
This issue seems to be resolved in [yesterday's experimental update](![image](https://user-images.githubusercontent.com/108291414/181816317-dbff5029-b99b-4cc8-9a84-3b975f84bf01.png)). I was not able to reproduce!

**Comment by MaFi-Games** [comment] 2022-08-20 13:56
Closing as not reproducible.

**Closed by MaFi-Games** 2022-08-20 13:56 UTC
Labels: could not reproduce
