### ISSUE TITLE
Getting water+power+household goods bonus after taking away household goods

### ISSUE THREAD

**Issue by bigsagebeast** [MaFi-Games/Captain-of-Industry-issues#1405] opened 2024-04-08 19:00 UTC
### Issue description

I've previously supplied water + power + household goods to my city, and then I paused my household goods module.  It still has inventory in it that's not being consumed. I'm correctly receiving no unity for household goods, but the +100% unity bonus is still highlighted.  I'm not sure how to tell if the +100% is being applied (or if it's reporting +100% but only applying +50%), but at minimum this is a display bug.

It interacts strangely with saved games - see repro steps.

### Reproduction steps

Open the attached saved game
Observe that the household goods module is paused, and the 100% bonus is being applied (incorrect)
Let the game run for a day
Observe the bonus has dropped to 50% (correct)
Unpause the household goods module
Observe the 100% bonus is being applied (correct)
Pause the household goods module again
Observe the 100% bonus is still being applied, even as time passes (incorrect)
[b.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/14910002/b.zip)

### Game version and build number

v0.6.0c (b319)

### Operating system

Windows

**Comment by zuff-coi** [comment] 2024-04-09 16:01
I was not able to reproduce this issue. I unpaused the building and observed the bonus going up, ran it for a day, then paused it and the bonus immediately went away. Can you verify you can reproduce this issue?
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/108291414/4f4b90e1-af93-4b5b-ab88-022e6310d5b0)

**Comment by zuff-coi** [comment] 2024-04-09 16:03
Was able to reproduce:
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/108291414/3f690df0-e9e3-4ce7-8004-12a7e3b9c847)

**Comment by MaFi-Games** [comment] 2024-05-02 16:58
Fixed in one of the last patches. Thanks!

**Closed as completed by MaFi-Games** 2024-05-02 16:58 UTC
Labels: bad behavior
