### ISSUE TITLE
Settlement water bulding can't be flipped

### ISSUE THREAD

**Issue by Bucktooth2** [MaFi-Games/Captain-of-Industry-issues#1221] opened 2023-08-05 11:53 UTC
### Issue description

When trying to place the water building for my settlement (Level 1) I can't flip it so that the clean water pipe in on the side i want it. When the building cursor is anywhere on the map, it can be rotated and flipped, as soon as i mouse over the yellow boundary of the placement squares it flips to its default rotation which can't be changed.
I've only noticed this with the settlement water building.

### Reproduction steps

Simple to reproduce in game

### Game version and build number

V0.5.3e (b225)

### Operating system

Windows

**Comment by MaFi-Games** [comment] 2023-08-05 13:14
Duplicate of #227

**Closed as not planned by MaFi-Games** 2023-08-05 13:14 UTC
