### ISSUE TITLE
Trucks gets stuck with no valid destination when running out of dumping area even when a storage building has room

### ISSUE THREAD

**Issue by Nightinggale** [MaFi-Games/Captain-of-Industry-issues#818] opened 2022-09-21 11:31 UTC
**The issue**
When emptying a storage building into a mining control tower, lots of trucks picks up slag (seen with dirt too) and goes to the dumping ground. Once there is no more room to dump, the trucks just hang around doing nothing, blocking them from getting new tasks. There is storage space available.

EDIT: I noticed that the green slider is not used in the savegame. However the first time I encountered this it was and I just tested it with the slider set to fill and no change. I won't bother to replace the savegame for that detail. Besides even with the green fill slider not being used, the trucks should still not silently get stuck.

**Expected behavior**
When free trucks fail to dump their cargo, they should as free trucks try to unload anywhere free trucks can unload. Getting stuck without warning is just waiting for the transport system to silently collapse due to loss of transports.

**To Reproduce**

1. load attached savegame
2. unpause the mine control tower
3. watch as trucks arrive from all over the map to load slag, drive to the dumping ground and then get stuck

**Additional context**
 - Game version: 0.4.12C (experimental branch), though I think it was 0.4.12A, where I observed this first.

**Attachments**
[Trucks stuck.save.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9616072/Trucks.stuck.save.zip)

**Comment by zuff-coi** [comment] 2022-09-21 15:01
Can confirm this. Even built a storage beside them with the slider set to keep full of slag and they were still stuck.

**Comment by mark5467** [comment] 2022-11-04 00:37
Can confirm as well. Trucks loaded with appropriate material right next to empty storage bin say no valid destination.  Also, trucks assigned to empty loose storage at dump will bring the material to dump back to the origin loose storage it was put in.

**Comment by MaFi-Games** [comment] 2022-11-26 18:13
This works as intended because you have assigned the storage to the tower. The trucks can't go to the other storage because they would break the assignment that the original storage has. Not having this enforcement in place would lead to other issues.

**Closed** 2022-11-26 18:13 UTC
Labels: bad behavior, logistics
