### ISSUE TITLE
Water facility connectors orientation

### ISSUE THREAD

**Issue by kingsepp01** [MaFi-Games/Captain-of-Industry-issues#1462] opened 2024-04-18 16:00 UTC
### Issue description

When changing the water facilities orientation (water left, waste water right) it flips back when docking to a settlement tile.

### Reproduction steps

1. Select water facility from building menu
2. Change orientation using f-Key
3. Try to dock it to a settlement tile
4. It changes orientation inside the green border and changes back when it is outside again (see GIF) 

### Game version and build number

v0.6.2a b328

### Operating system

Windows

### Attachments

![Water_facility_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/96915476/7e8bf6e1-eba7-49d2-a637-7852884aae1c)

**Comment by MaFi-Games** [comment] 2024-04-18 17:16
Duplicate of #227

**Closed as not planned by MaFi-Games** 2024-04-18 17:16 UTC
