### ISSUE TITLE
Save Game Crash

### ISSUE THREAD

**Issue by wik0007** [MaFi-Games/Captain-of-Industry-issues#686] opened 2022-08-08 07:25 UTC
### Issue description

A number of times the game crashes, usually around time when it tries to do an Auto Save.

This time the save function crashed, but not the game. I was unable to manually save the game either. I was given an undefined object error.

I have attached a screen capture of the error.
![Captain of Industry Save Bag](https://user-images.githubusercontent.com/110811065/183361911-2666f22d-9ed8-45ee-b732-6a26c7be321e.jpg)

### Expected behavior

I expected the game to save either by overwriting an existing file or by saving a new file.

### Reproduction steps

Unable to assist. The game randomly does this. The undefined object error is the first time it has happened to me and I do not know how to reproduce it.

### Game version

v0.4.9c

### Attachments

[22-08-08_12-50-02_2003.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9279680/22-08-08_12-50-02_2003.log)
[22-08-08_05-11-12_5945.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9279688/22-08-08_05-11-12_5945.log)
[22-08-08_05-21-31_0111.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9279689/22-08-08_05-21-31_0111.log)
[22-08-08_05-22-15_1114.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9279690/22-08-08_05-22-15_1114.log)
[22-08-08_05-26-24_4472.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9279691/22-08-08_05-26-24_4472.log)
[22-08-08_05-27-55_2210.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9279692/22-08-08_05-27-55_2210.log)
[Player-prev.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9279696/Player-prev.log)
[Player.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9279697/Player.log)

[22-08-08_06-57-05_8961.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9279694/22-08-08_06-57-05_8961.log)
![Captain of Industry Save Issue](https://user-images.githubusercontent.com/110811065/183362838-982b4d47-3db1-4f9b-81b1-10844d96e582.jpg)

**Comment by zuff-coi** [comment] 2022-08-08 15:55
This sometimes happens with Windows Ransomware Protection being on
![image](https://user-images.githubusercontent.com/108291414/183460394-2340d96c-8fe1-40d7-9030-6b14a3719d92.png)
![image](https://user-images.githubusercontent.com/108291414/183460434-6f3b86a6-1b4b-4d8b-a29c-5c2a54662103.png)

This can prevent the application from accessing the Documents folder. Could you check and see if that is on? If so, turn it off and see if the issue persist.

**Comment by wik0007** [comment] 2022-08-09 08:30
Hi Zuff-Coi,

I have just verified that the controlled folder access is off.

**Comment by MaFi-Games** [comment] 2022-08-10 16:05
There is definitely something bad happening. And I have not seen this before.

Could you please provide us your save files that are hitting this? I for instance see "22-08-08_13-05-autosave.save"

I can see the following in logs:

X 06:47:23,770 S1144589 ~Sim: Exception thrown in event callback.
 ---> NullReferenceException: Object reference not set to an instance of an object
  at Mafi.Core.PathFinding.VehiclePathFinder.continuePathFinding (System.Int32& stepsLeft, System.Boolean newTaskStartedThisSimStep)  
  at Mafi.Core.PathFinding.VehiclePathFinder.ContinueVehiclePathFinding (System.Int32& iterations, System.Boolean newTaskStartedThisSimStep, System.Boolean isFinalAttempt)  
  at Mafi.Core.PathFinding.VehiclePathFindingManager.updatePathFindingTasks ()  
  at Mafi.Core.PathFinding.VehiclePathFindingManager.update ()  
  
  X 07:05:23,317 S1155064 ~Mai: Failed to save game.
 ---> NullReferenceException: Object reference not set to an instance of an object
  at Mafi.Serialization.BlobWriter.TryStartClassSerialization[T] (T obj)  
  at Mafi.Core.PathFinding.ClearancePathabilityProvider+CapabilityChunkData.Serialize (Mafi.Core.PathFinding.ClearancePathabilityProvider+CapabilityChunkData value, Mafi.Serialization.BlobWriter writer)  
  
  X 21:26:46,041 S------ ~Mai: Invocation of init action 'initSelf' on 'TerrainManager' failed.
 ---> TargetInvocationException: Exception has been thrown by the target of an invocation.
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)  
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters)  
  at Mafi.Serialization.BlobReader.invokeInit (Mafi.Serialization.BlobReader+InitAfterLoad initData, Mafi.Option`1[T] resolver) [0x0018a]  
  at Mafi.Serialization.BlobReader.FinalizeLoading (Mafi.Option`1[T] resolver)  
 ---> NullReferenceException: Object reference not set to an instance of an object
  at Mafi.Collections.Lyst`1[T].get_Last ()  
  at Mafi.Base.Terrain.DirtOnRocksTerrainPostProcessor.PostProcessGeneratedIslandMap (Mafi.Core.Map.IslandMap map, Mafi.Core.Terrain.Generation.GeneratedTerrainData terrainData) [0x000c3]  
  at Mafi.Core.Terrain.Generation.TerrainGenerator.GenerateAndPostProcessTerrain ()  
  at Mafi.Core.Terrain.TerrainManager.generateTerrain (System.Boolean gameIsBeingLoaded)

**Comment by drewstur** [comment] 2022-08-15 13:51
I'm getting the same error. Sadge.

**Comment by MaFi-Games** [comment] 2022-11-24 17:33
Duplicate of #757

**Closed by MaFi-Games** 2022-11-24 17:33 UTC
Labels: bug, high priority, needs investigation
