### ISSUE TITLE
Unable to select a truck stuck on a bridge

### ISSUE THREAD

**Issue by Astree13** [MaFi-Games/Captain-of-Industry-issues#117] opened 2022-01-15 18:16 UTC
**Describe the issue**
Truck on a bridge is impossible to select, as it can't reach its target

**To Reproduce**
In the save, see the bridge just next to the food storage

**Expected behavior**
Wanted to get it back as it is targeting a wrong target

**Additional context**
game 0.3.10

**Attachments**
save file and screenshot
[save_22-01-15_19-09-32.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7875548/save_22-01-15_19-09-32.zip)
![image](https://user-images.githubusercontent.com/34662883/149633120-77b46d07-b036-4309-b727-89df97602ba6.png)

**Comment by MaFi-Games** [comment] 2022-11-26 17:17
Duplicate of #339

**Closed by MaFi-Games** 2022-11-26 17:17 UTC
Labels: bad behavior, beta issue
