### ISSUE TITLE
Pipes goes optic illusion

### ISSUE THREAD

**Issue by Smedorin** [MaFi-Games/Captain-of-Industry-issues#618] opened 2022-07-24 11:22 UTC
### Issue description

Hello, I discovered an optical illusion. i built the pipes, removed the last support and then changed the direction of the flow. The pipes were then displayed as built under the pipes that had already been laid. but the pipes are not built, i can build new pipes through them. After a few days i resumed the game in "paused", build the pipes, unpaused the game the first time. the illusion build Pipies go up into dust. i played a little bit with the pipes, and now i had a new beam. is this optic normal?

### Expected behavior

i don't now. :D

### Reproduction steps

Savegame: [Smedo_EEA_Canary_Curland.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9175653/Smedo_EEA_Canary_Curland.zip)
Pictures of the Pipes: [Pipes_goes_optic_illusion.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9175656/Pipes_goes_optic_illusion.zip)

### Game version

v.0.4.8

### Attachments

[Smedo_EEA_Canary_Curland.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9175657/Smedo_EEA_Canary_Curland.zip)
[22-07-23_21-55-43_3200.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9175658/22-07-23_21-55-43_3200.log)
I don't know if the Log Data is sufficient, because i played 2 hours after the "optic illusion"

**Comment by MaFi-Games** [comment] 2022-12-01 23:51
Thanks for the report. I was trying to reproduce this in our upcoming patch but I was unable to reproduce.

To confirm, the steps to get these strange pipes were:
1. Build a pipe (possibly below other pipes).
2. While still in a blueprint, remove the last part of the pipe that has a pillar.
3. Reverse direction.

I will mark this as potentially fixed, if that is not the case, feel free to comment or file a new report. Thanks!

**Comment by zuff-coi** [comment] 2022-12-23 18:11
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.

**Closed by zuff-coi** 2022-12-23 18:11 UTC
Labels: bug, triage, fixed in v0.4.13
