### ISSUE TITLE
Savegames not showing at first start

### ISSUE THREAD

**Issue by sharkking76** [MaFi-Games/Captain-of-Industry-issues#296] opened 2022-06-10 20:00 UTC
**Describe the issue**
2 Times i had the issue that Savegames are not shown when starting the game. It works after restarting the Game.
Now they won´nt show up at all. 

**Expected behavior**
Savegames should show up

**To Reproduce**
1. Start the Game
2. Continue Button is greyed out
3.  Klick in Load shows empty savegame list

**Additional context**
 - Game version: 0.4.2a and 0.4.3, German Translation

**Attachments**

![bug#2](https://user-images.githubusercontent.com/75562589/173141766-8e47d2db-a7b1-4bc4-a07c-2985e48cff4a.PNG)
![bug#1](https://user-images.githubusercontent.com/75562589/173141770-0f3679d3-d5e6-45ab-a9d9-af1df7f60ceb.PNG)

**Comment by MaFi-Games** [comment] 2022-06-15 10:57
Thanks for reporting. There is something strange happening with the directory being randomly remaped to SteamApps, you might be able to find your saves in Documents & Settings and copy them there. Please take a look here for more info until we figure out how to fix this: https://github.com/MaFi-Games/Captain-of-Industry-issues/issues/252

**Comment by MaFi-Games** [comment] 2022-06-16 23:31
Duplicate of #252

**Closed as completed** 2022-06-21 10:28 UTC
