### ISSUE TITLE
Vehicles are freezing for several seconds

### ISSUE THREAD

**Issue by JasherFission** [MaFi-Games/Captain-of-Industry-issues#574] opened 2022-07-15 01:40 UTC
### Issue description

The vehicles in the game now are freezing for several second when they seem to be trying to think about what to do or where to go.  I have about 110 vehicles in my save file, but ever since the update is when they started to freeze up.

### Expected behavior

The vehicles before would almost immediately move to new locations to mine or to move around materials.

### Game version

v0.4.8

### Attachments

[Stream Restart.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9116988/Stream.Restart.zip)

**Comment by ParanoikCZE** [comment] 2022-07-15 06:53
Possibly another duplicate of #364, but the description isn't too clear.

**Comment by JasherFission** [comment] 2022-07-15 08:35
no its definitely different, because its not just the trucks that are stopping but also the tree harvesters and the excavators that stop.  It does not matter whether the game is moving at a faster speed or not, the vehicle will usually freeze up after performing an action (picking up resources, preparing to move, etc) and will preparing to perform another command.

**Comment by zuff-coi** [comment] 2022-07-15 14:16
Can confirm it's a duplicate of #364 

What's happening is when large storages are in place and multiple vehicles are accessing it, they create a line. Only one vehicle can access the storage at a time so when it does, the others wait to see if the job will still be available after that vehicle uses it (eg. if it's full or not)

A temporary solution for this is to use multiple smaller storages to provide backup locations for the vehicles to access, like this:
![image](https://user-images.githubusercontent.com/108291414/179241600-bff8c45b-fe07-4128-91ba-9cdd267ace77.png)

You can still feed them into the large storage and if a truck see's one of the storages is being accessed it will continue on to the next one.

**Closed by zuff-coi** 2022-07-15 14:16 UTC

**Comment by zuff-coi** [comment] 2022-07-29 14:54
We [released an update on the experimental branch](https://steamcommunity.com/games/1594320/announcements/detail/3397421255147457180) which has fixes aimed at this issue. If you could please try it out and let us know if your issue is resolved that would be great!
