### ISSUE TITLE
Haul Truck Tank , returns to fuel station after each fill , not when empty 

### ISSUE THREAD

**Issue by DemBones78** [MaFi-Games/Captain-of-Industry-issues#1237] opened 2023-08-24 03:39 UTC
The Haul Truck Tank, returns to the fuel station after each fill, not when empty

**Comment by JamieRCHI** [comment] 2024-02-07 13:07
Time to close this maybe? By Design?

**Comment by MaFi-Games** [comment] 2024-04-18 17:34
Yeah, this is by design.

**Closed as not planned by MaFi-Games** 2024-04-18 17:34 UTC
Labels: works as intended
