### ISSUE TITLE
Lack of Water Pipe Collision/Need Buildable Roads

### ISSUE THREAD

**Issue by Sjs06** [MaFi-Games/Captain-of-Industry-issues#430] opened 2022-06-25 13:04 UTC
I have placed a LONG diesel pipe stretching to the far reaches of the map. Part of the piping system is next to a cliff edge with no space for trucks to drive around between the pipe and cliff (intended). However, the trucks drive along the pipes, and will **literally** cut the corner of the pipe, clip through the pipe's corner, and get trapped because there is no space for them to drive. I am constantly recovering trapped trucks. 

To solve this issue, I have placed concrete barriers a few spaces away from the pipe, but two issues have arised. 1) The trucks are still cutting the corner of the barriers the same way as with the pipes, and 2) the trucks now seem to have an issue with pathing because they will drive a few paces, then stop for a bit, then resume driving. 

A good solution for this issue could be to add roads for the trucks to drive on. Concrete could be used, or asphalt could be added as a produced item. 

**Expected behavior**
I expected both the pipes and concrete barriers to have proper collision, so that the trucks avoid these items by a few paces and cannot clip through them. Driving into a concrete barrier is obviously not a good idea... 

**To Reproduce**
1. Load attached save
2. At the top of the map with the factory setup (opposite side of map from shipyard), you can find my diesel piping. Simply watching the trucks drive along the pipes will produce the corner clipping issue, but it may take some time before a truck gets properly stuck from clipping. 

**Additional context**
 - Game version: 0.4.5b

**Attachments**
[Save 2.zip] (https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8984759/Save.2.zip)

**Comment by dgzeij** [comment] 2022-06-25 16:34
I notice this aswell on random places. Can look like the trucks don't look for viable driving space when backing up to turn around. The two issues with that is the truck mistakenly thinks there is drivable space through a pipe, then the game allows it to drive there. More prone to happen at pipe corners/bends. Maybe it checks for obstacles in a straight line instead of a curve which is the planned route.

**Comment by Sjs06** [comment] 2022-06-28 18:26
FML
https://gyazo.com/ab2125e276f35f07e152cff3eb28a446

**Comment by MaFi-Games** [comment] 2022-11-26 17:51
Duplicate of #338

**Closed by MaFi-Games** 2022-11-26 17:51 UTC
