### ISSUE TITLE
Tree harvester stuck, can't select it

### ISSUE THREAD

**Issue by aresch** [MaFi-Games/Captain-of-Industry-issues#862] opened 2022-10-06 00:14 UTC
### Issue description

I built a farm on top of where a tree harvester that was waiting for a truck to load it's log. Now the truck can't reach the harvester and I can't select the harvester to recover it since it just selects the farm instead.

### Expected behavior

I would expect the tree harvester to move once the farm was built where it was waiting or at least being able to select the harvester and tell it to move or recover.

### Reproduction steps

1. Load the attached save.
2. Try to do anything to get my harvester out of the way :)

### Game version

v0.4.12c

### Attachments

[harvester.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9719700/harvester.zip)

**Comment by zuff-coi** [comment] 2022-10-07 13:09
Can confirm this. The only way to get the harvester at the moment is to deconstruct the farm. Harvester needs to move when ghost placed on top of it.

**Comment by MaFi-Games** [comment] 2022-11-26 17:20
Duplicate of #339

**Closed by MaFi-Games** 2022-11-26 17:20 UTC
Labels: bug, Back log
