### ISSUE TITLE
Trucks stop while recalculating after drop off by other truck of carried good

### ISSUE THREAD

**Issue by mnoreke** [MaFi-Games/Captain-of-Industry-issues#364] opened 2022-06-17 11:23 UTC
**Describe the issue**
With a large base, when trucks drop off items in a storage, other trucks with the same cargo stop, wait, recalculate, and then start again. With many trucks, this becomes more obvious.

**Expected behavior**
Trucks should be able to continue driving while recalculating.

**To Reproduce**
1. Load attached save 'TrucksStopping'
2. Monitor coal deliveries 
3. See other coal trucks stop

**Additional context**
 - Game version: 0.4.4c

**Attachments**
[TrucksStopping.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8926987/TrucksStopping.zip)

**Comment by zuff-coi** [comment] 2022-07-12 17:03
This issue is widely known and is caused by the queuing system of the trucks. Only one truck can access a storage at a time and when the storage is accessed, the other trucks queue wait to see if the job is still available once the access is done. 

This can cause a line of trucks performing one job to "pause" while they wait for the storage to be done servicing the current vehicle in front of the line.

A temporary solution to this issue is to build multiple storages (small and medium work best) and trucks waiting in line will move on to the next storage if the one they were assigned to is busy.

**Comment by ManueldeHeer** [comment] 2022-07-12 21:33
That's not a solution, I've tried that and the trucks can't keep up with the demand, causing production problems. I make frequent use of large storage facilities from which several factories receive deliveries. Couldn't play for two weeks now. because this is a serious problem!

**Comment by zuff-coi** [comment] 2022-07-29 14:51
We [released an update on the experimental branch](https://steamcommunity.com/games/1594320/announcements/detail/4972554042131344663) which has fixes aimed at this issue. If you could please try it out and let us know if your issue is resolved that would be great!

**Closed** 2022-11-24 17:27 UTC
Labels: bad behavior, logistics
