### ISSUE TITLE
Error loading save file.

### ISSUE THREAD

**Issue by twnkysxtnine** [MaFi-Games/Captain-of-Industry-issues#407] opened 2022-06-22 03:53 UTC
**Describe the issue**
Save file doesn't load.  Attached are the save file and log.  Or I would attach the save file but its 34MB and limit is 25.  I'm Twinky69 in your discord if you wish to dm me and let me know other ways to get you the save file

**Expected behavior**
Explain what you expected to happen.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]

**Attachments**

[22-06-21_20-56-11_2657.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8954240/22-06-21_20-56-11_2657.log)

**Comment by dgzeij** [comment] 2022-06-23 14:12
Same here.

At one point shortly after the last good savefile all the future saves are deemed corrupt by the game.

This is the last save the game is accepting:
[save_22-06-17_09-50-33 _fresh_water to nuclear reactor.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8967910/save_22-06-17_09-50-33._fresh_water.to.nuclear.reactor.zip)

The last save of the second time I tried playing from the last good savefile:
[save_22-06-21_16-56-49 nuke to power.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8967943/save_22-06-21_16-56-49.nuke.to.power.zip)
Log from when starting game -> attempting to load this save once -> exit game on error:
[Player.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8967946/Player.log)

Logs from testing all available savefiles after last good:
[Player.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8967954/Player.log)
[Player-prev.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8967955/Player-prev.log)

Last 4 autosaves (missing ballpark 30-60 min playtime between save_22-06-17_09-50-33._fresh_water.to.nuclear.reactor and 22-06-21_16-03-23_0336-autosave):
[22-06-21_16-03-23_0336-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8967969/22-06-21_16-03-23_0336-autosave.zip)
[22-06-21_16-18-23_1213-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8967991/22-06-21_16-18-23_1213-autosave.zip)
[22-06-21_16-33-23_2065-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8967994/22-06-21_16-33-23_2065-autosave.zip)
[22-06-21_16-48-23_2558-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8967996/22-06-21_16-48-23_2558-autosave.zip)

Let me know if you need more info.

Atm I can't play any further since something corrupts the save shortly after save_22-06-17_09-50-33._fresh_water.to.nuclear.reactor

**Comment by dgzeij** [comment] 2022-06-23 15:05
Just tested to continue on the last working save, then build one of the 3 new buildings I haven't built before in the game to see if one of them separately was the cause of load corruption. None of square (dark), nuclear reactor or spent fuel storage caused any errors.

Verifying integrity of game files @ Steam didn't help.

Doing some quick autosaves now with mining only, similar to the last two save branches, to see if that part was the cause.

**Comment by dgzeij** [comment] 2022-06-23 19:06
Pinpointed my crash point to when dumping waste here +/- a couple tiles @ the map You Shall Not Pass:
![20220623204941_1](https://user-images.githubusercontent.com/85814950/175376871-402e979a-4bd6-4999-abd7-79f01fdea668.jpg)

A few tiles away on either sides don't produce any errors. Could dump all 11k waste on both sides without errors while error occured on this corner after less than 2k waste. Everything else was constant, nothing else could cause the error.

Starting point waiting to start dumping and produce error:
[save_22-06-23_19-48-06 waited few mins before dumping waste.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8970202/save_22-06-23_19-48-06.waited.few.mins.before.dumping.waste.zip)
First truckload didn't cause error:
[save_22-06-23_20-50-03 waste dump corner first truck loads.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8970203/save_22-06-23_20-50-03.waste.dump.corner.first.truck.loads.zip)
When 9k waste left the save was deemed corrupted:
[save_22-06-23_20-51-47 waste dump corner 9k left.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8970206/save_22-06-23_20-51-47.waste.dump.corner.9k.left.zip)

[Player.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8970199/Player.log)

**Comment by MaFi-Games** [comment] 2022-06-25 21:13
Thanks for the fantastic report! We have identified problem and working on a fix. If everything goes well there should be a patch ready today or tomorrow.

**Comment by MaFi-Games** [comment] 2022-06-28 02:36
This has been fixed in v0.4.6

**Closed by MaFi-Games** 2022-06-28 02:36 UTC
Labels: bug, high priority
