### ISSUE TITLE
Water facility (and food market) doesn't respect mirror image

### ISSUE THREAD

**Issue by kwolkan** [MaFi-Games/Captain-of-Industry-issues#377] opened 2022-06-19 10:04 UTC
**Describe the issue**
It is not possible to put a Water Facility in mirror image version (i.e. looking from the side of pipes input/output to have waste water on the right). I also checked food market and it displays the same behaviour, not sure about any other settlement facilities, but I feel it might be the same story.

**Expected behaviour**
I expect mirror image of the building to be available. When building is not snapped to the settlement it is possible to see (on the blueprint) mirrored version, but as soon as it snaps to the settlement, it swaps.

**To Reproduce**
1. Select one of the settlement facilities (such as water facility)
2. Hit 'F' to select mirror image (swapping placement of the in/output ports)
3. Place the building next to the settlement
4. Observe the ports go back to the original layout

**Additional context**
 - Game version: 0.4.4c

**Comment by MaFi-Games** [comment] 2022-11-26 22:39
Duplicate of #227

**Closed by MaFi-Games** 2022-11-26 22:39 UTC
Labels: feature request, works as intended, back log
