### ISSUE TITLE
Conveyor sorter can't handle tier III belt at full speed

### ISSUE THREAD

**Issue by HardCoreGaming** [MaFi-Games/Captain-of-Industry-issues#570] opened 2022-07-14 09:03 UTC
**The issue**
Tier 3 belt can't work at full speed with conveyor sorter. A simple blueprint to reproduce this is described in the screenshot.

**Expected behavior**
Full speed tier 3 belt.

**To Reproduce**
Describe steps to reproduce the issue here, for example:
1. Load attached save [sorter.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9110275/sorter.zip)
2. You get full belt before sorter and not full belt after sorter even all resourses sorted to one side.
3. Maybe this issue appears on highly loaded factories, so I'm attaching my save.

**Additional context**
 - Game version: [0.4.8]

**Attachments**
If applicable, attach a save file (zipped), screenshots, or log files to help us resolve the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like a crash or rendering glitches, also include Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. Thanks for taking your time writing this report!
![2035-mMQK7Fj7](https://user-images.githubusercontent.com/78960081/178944974-04003f82-3586-4f70-8a7d-d5f858720058.jpg)

**Comment by ParanoikCZE** [comment] 2022-07-14 09:59
Duplicate of #459

**Closed** 2022-07-14 11:26 UTC
