### ISSUE TITLE
 Lab equipment that is deliver via trucks to Research Labwont get delivered

### ISSUE THREAD

**Issue by knmh84** [MaFi-Games/Captain-of-Industry-issues#485] opened 2022-07-03 05:29 UTC
the storage wont get empty of Lab equipment that is deliver via trucks to Research Lab
attach is the save file
and all test screenshots with it

![lab test](https://user-images.githubusercontent.com/106634630/177026176-06d7e1d0-91c0-4e98-8d2d-ab0e4398f688.png)
![lab test (2)](https://user-images.githubusercontent.com/106634630/177026190-546fef81-7ba6-4356-96e2-431d6c2b1499.png)
![lab test (3)](https://user-images.githubusercontent.com/106634630/177026195-7ab82318-4c20-4e7b-b77a-ebb7ad1aaf44.png) 
![lab test (4)](https://user-images.githubusercontent.com/106634630/177026199-39ae4158-2c4f-45fa-a0a8-e802269aac12.png)
![lab test (5)](https://user-images.githubusercontent.com/106634630/177026204-069e9c7a-dcd2-4000-adf5-a31c0b0092c8.png)
![lab test (6)](https://user-images.githubusercontent.com/106634630/177026214-86291e4e-e0e6-49af-a247-67c3b5a605ab.png)

[Lab equipments transfer issue.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9034127/Lab.equipments.transfer.issue.zip)

**Comment by BLADERUNNER1987** [comment] 2022-07-05 02:14
Looks like maybe it was fixed.  I reported something similar if not exactly the same.  The problem is when you disable partial truck loads.

https://github.com/MaFi-Games/Captain-of-Industry-issues/issues/375

**Comment by MaFi-Games** [comment] 2022-07-05 10:09
This has been fixed in v0.4.7b, thanks for the report.

**Closed by MaFi-Games** 2022-07-05 10:09 UTC
Labels: work in progress
