### ISSUE TITLE
Save game location changing every other day

### ISSUE THREAD

**Issue by FelipeAlves99** [MaFi-Games/Captain-of-Industry-issues#775] opened 2022-09-06 09:32 UTC
### Issue description

My game save files keep switching between **Documents\Captain of Industry\Saves** and **Steam\steamapps\common\Captain of Industry\Captain of Industry\Saves** when starting the game.

### Expected behavior

Keep the saves in the same place

### Reproduction steps

I don't know how to reproduce, because it randomly chooses one of the location every time I open the game

### Game version

v0.4.11

**Comment by MaFi-Games** [comment] 2022-11-26 17:45
Duplicate of #896

**Closed by MaFi-Games** 2022-11-26 17:45 UTC
Labels: bug, needs investigation
