### ISSUE TITLE
Underground pipes being disconnected when building transports on top.

### ISSUE THREAD

**Issue by BainrowKiss** [MaFi-Games/Captain-of-Industry-issues#355] opened 2022-06-16 07:38 UTC
**Describe the issue**
Title; As far as I can tell, when the support columns of a pipe (possibly any transport) above ground lands on an underground pipe, it will disconnect the underground one by removing parts of the pipe. 

**Expected behavior**
I expect the underground pipes to remain intact no matter what you build on top, except for power generator and flywheel.

**To Reproduce**
1. Load the attached savegame "underground pipes disconnect"
2. By the seawater factory there's a planned fluid tank.(Save should load in at this spot) Build a pipeline from the free connection on the planned fluid tank to the boiler(coal) system and it will disconnect the underground pipe running from the planned fluid tank in front of cargo depot and fluid module. 
3. This keeps happening other places as well. 

**Additional context**
 - Game version: Early access 0.4.4b

**Attachments**
[Underground pipes disconnect.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8916668/Underground.pipes.disconnect.zip)

**Comment by RonchiDonkey** [comment] 2022-06-16 13:19
I can confirm that it is any transport, including planning mode. It appears to be trigger by a column collision when the transport you are installing above ground places a column in the same location as a below ground pipe has place a column.

**Comment by BainrowKiss** [comment] 2022-06-26 14:02
Really hope we'll get to see a fix for this in the next update/patch. I completely stopped using underground pipes after having a lot of problems with disconnections everywhere. 
Such a cool feature though! I love how much time it takes to dig up everything to lay the pipes and fill it back up again, feels like a proper project and everything gets so neat when it's done.

**Comment by BainrowKiss** [comment] 2022-06-27 22:28
New patch fixed the dirt getting removed when upgrading, but no fix for underground pipes getting disconnected yet. Hopefully in the next patch!

**Comment by RonchiDonkey** [comment] 2022-06-29 19:27
Has this issue been acknowledged or reviewed at all ?

**Comment by BainrowKiss** [comment] 2022-06-30 08:55
> Has this issue been acknowledged or reviewed at all ?

Not as far as I can tell. Made a post on the bug sub forum on steam asking for some feedback.

**Comment by BainrowKiss** [comment] 2022-07-09 08:53
Devs are well aware and a fix is planned. We just don't know when. Hoped my "short break until they fix this issue" would last a couple of days, tops, but here we are ten days later..

**Comment by MaFi-Games** [comment] 2022-11-30 09:01
Thanks for reporting. We have finally found out the root cause of this issue. It will be fixed in the next patch!

**Comment by BainrowKiss** [comment] 2022-11-30 10:31
Great news for a great game! Thanks for the hard work!

**Comment by zuff-coi** [comment] 2022-12-23 18:13
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.

**Closed by zuff-coi** 2022-12-23 18:13 UTC
Labels: bad behavior, fixed in v0.4.13
