### ISSUE TITLE
Raised Pipe/Belt Supports not rendering as built after construction

### ISSUE THREAD

**Issue by ukjohnd** [MaFi-Games/Captain-of-Industry-issues#793] opened 2022-09-15 21:13 UTC
### Issue description

When building raised Pipes/Belts  normally or with unity the supports are not rendering as built when pipe/belt completes build.
After saving and loading game, supports are rendered OK.
![2022-09-15 21_43_02-Window](https://user-images.githubusercontent.com/31622605/190509463-a924ac58-2a88-455b-b47e-0cbd56202e1e.png)

### Expected behavior

Supports to show as built,

### Reproduction steps

Create raised Pipe/Belt and build

### Game version

v.0.4.12 (experimental) 

### Attachments

[Goldencap gold + concrete 4.12 git.save.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9579107/Goldencap.gold.%2B.concrete.4.12.git.save.zip)

**Comment by RealisticOptimist** [comment] 2022-09-16 01:54
I can confirm.
Maybe someone changed something due to #774?

**Comment by MaFi-Games** [comment] 2022-09-17 18:29
This was fixed in v0.4.12a, thanks for reporting!

**Closed by MaFi-Games** 2022-09-17 18:29 UTC
