### ISSUE TITLE
All mines at the beginning

### ISSUE THREAD

**Issue by Kalti811** [MaFi-Games/Captain-of-Industry-issues#1487] opened 2024-04-28 17:24 UTC
### Issue description

After loading a savegame of an edited map. The mine status is not loaded. All the mines look as if nothing had been mined.

### Reproduction steps

1.Loading save file "Kalti Industry>Test 1.1" map Salvara Isla.
2.After loading, see the map.
3.All mine mining areas look unused.This refers to the two mines for coal and iron.
![20240428190456_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/168361819/50144602-2134-44ae-a172-041895d6ef65)

### Game version and build number

v0.6.3a b333

### Operating system

Windows

### Attachments

[Kalti Industry all.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/15142989/Kalti.Industry.all.zip)

**Comment by Kalti811** [comment] 2024-04-28 18:06
Another save game map Armageddon has the same problem. I played on ultra high. After I set the setting to balanced everything was back to how it should be. I also noticed that it's an anti-aliasing problem. With high msaa x2 there is no problem, only from msaa x4.Ultra high with msaa x2 is the problem also there. Ultra high with smaa the problem is no longer there. So it will be an anti aliasing problem.

**Comment by Kalti811** [comment] 2024-04-28 18:47
I've tried all the settings on the map and they all have the error. 
maybe it's because of the costem mad map.

**Comment by MaFi-Games** [comment] 2024-05-02 16:49
I just tried this on my side and the terrain seems to be mined as it should. Does this always happen 100% time? Could you please also attach your logs so we can take a look if there are some issues.

![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/90082857/00a3d63c-40e5-4c19-ae56-d964f50e7f71)

**Comment by Kalti811** [comment] 2024-05-03 02:42
[Logs.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/15195705/Logs.zip)

Here are the logs from today. At the last one everything was in place. The error was found in the first one.For the others, the program closed without an error message

my Cpu is Intel(R) Core(TM) i9-14900KF   3.20 GHz
My GPU is Nividia Geforce RTX 4090
Ram 64GB
And system Win 11

**Comment by MaFi-Games** [comment] 2024-05-08 01:25
Thank you for the detailed report and attached files/logs. We have been able to reproduce this issue and fix will be available in the next patch.

**Comment by CaptainMarek** [comment] 2024-05-09 04:42
This was fixed in v0.6.3b.

**Closed as completed by CaptainMarek** 2024-05-09 04:42 UTC
Labels: fixed in next patch
