### ISSUE TITLE
Assigned Trucks Are Not Prioritized

### ISSUE THREAD

**Issue by utdrmac** [MaFi-Games/Captain-of-Industry-issues#406] opened 2022-06-22 03:23 UTC
**Describe the issue**
When a truck is assigned to a storage container, and 'Accept Assigned Only' is NOT checked, the assigned truck is not prioritized to be picked for delivery/empty task.

**Expected behavior**
I expect that an assigned truck takes highest priority when a delivery needs to occur

**To Reproduce**
1. Create storage bin, mine tower, and dump zone
2. Link bin to export to tower
3. Assign a truck to the storage bin
4. Fill bin.

Assigned truck will remain nearby bin and will not take a load. Wait a bit and another "public" truck will come and take the load.

**Additional context**
 - Game version: 0.4.5b
 
** Saved Game**
When you load this game, fly over to the ocean near the salt maker and you'll see a trash bin and a yellow truck. The truck is assigned to the bin. Notice there is more than 60 in the bin but the truck isn't taking it. Wait a bit and another truck will come along and take a load. This should not happen. The yellow assigned truck should always be working unless there's too much in the bin, then another should be assigned.

[trucksNotDelivering.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8954138/trucksNotDelivering.zip)

**Comment by utdrmac** [comment] 2022-06-24 01:39
This is not a feature request. This is a design bug in the truck priority system. Several others have also reported same behavior. Tell me then, what's the point of assigning a truck to a task if that is simply going to be ignored?

**Comment by MrJoshua023** [comment] 2022-06-24 02:17
Not a bug, but definitely not good behavior.  Assigned trucks should always be first in queue before the general truck pool.  Otherwise they just sit there idle doing nothing.

**Comment by JamieRCHI** [comment] 2022-06-25 19:37
> Not a bug, but definitely not good behavior. Assigned trucks should always be first in queue before the general truck pool. Otherwise they just sit there idle doing nothing.

I say it is a Bug.

**Comment by Cengro** [comment] 2022-07-13 21:10
Same issue is happening to me as well. I reported this on Discord too. You assign 2 trucks to route and the trucks just sit there and do nothing.

**Comment by MaFi-Games** [comment] 2022-11-25 17:41
Thanks for your report. This was fixed in v0.4.9

**Closed by MaFi-Games** 2022-11-25 17:41 UTC
Labels: bad behavior, feature request
