### ISSUE TITLE
Lots of log spam causing frequent game hiccups

### ISSUE THREAD

**Issue by SyxeDev** [MaFi-Games/Captain-of-Industry-issues#880] opened 2022-10-27 08:04 UTC
Question - Is there a way for me to supress certain types of logs like Warning and Information? 

Reproduction steps - unable to determine precise steps (sorry! keeping an eye out for when it happens next)

End User Context - I was planning out retaining walls for my coal deposit using retaining wall ghosts (build mode enabled) and using mining/dumping to lay it out. After awhile of planning, I unpaused the game, and switched tasks to planning/making more industry. Right around this transition period was when I noticed frequent game hiccups; maybe 0.5-1seconds of game freeze every 5-10 seconds. It felt like heavy Unity Garbage Collection, but I noticed lots of warning 'W' level logging in the log file. 

The log file is rather spammy, but if you search for 'S441952'  it will show 3 Assert entries in the logfile. Entries before this were me loading the game/save and planning retaining walls. Entries after line closely/exactly line up to when the game stuttering/hiccups started. 

Another important piece but maybe different piece of this puzzle is at the very end of the logfile 'S454618' . I opened my console and ran the 'also_log_to_console' command. I saw a spam of W/warning level events and then all logging stopped, both to file and console. I know this to be true because I ran the console command at 2:15 or 2:16 (logtime), but the file didnt record 'also_log_to_console' until i ran the command again to turn it off at 2:22.

Workarounds: 
- Restart game and reload save.
- (sometimes maybe) run the 'also_log_to_console' command (because it appeared to stop logging entirely)

[log.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9875229/log.zip)
[Player-prev.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9876995/Player-prev.zip)

**Comment by laino** [comment] 2022-11-16 02:54
I had the exact same issue after laying out some retaining walls.

On a hunch I disabled ``Error reporting`` in the game settings and the hiccups went away.

Seems obvious what's going on.

**Comment by MaFi-Games** [comment] 2022-11-22 13:48
Error causing this:
`S444424 ~Sim: Layer is being removed but it was not present.
  at Mafi.Unity.Terrain.TerrainChunkRenderer.removeDetails (Mafi.Core.Products.DetailLayerSpecProto detailLayerProto, System.Int32 tileDataIndex)  `

**Comment by MaFi-Games** [comment] 2022-11-22 13:48
duplicate of #844

**Comment by MaFi-Games** [comment] 2022-11-22 13:49
Duplicate of #844

**Closed by MaFi-Games** 2022-11-22 13:49 UTC
