### ISSUE TITLE
Ship yard not unloading

### ISSUE THREAD

**Issue by Krenan** [MaFi-Games/Captain-of-Industry-issues#7] opened 2021-09-18 08:42 UTC
**Describe the issue**
Toggle is on to unload but it will not unload. I thought maybe I didn't have storage locations for it to unload but Slag will not move. Mod said to upload the save file.
[For Devs 9-18-2021.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7189575/For.Devs.9-18-2021.zip)

Krenan - Alpha

**Comment by MaFi-Games** [comment] 2021-09-26 06:19
Thanks for the report, the issue is that there is too small quantity so trucks are "lazy" and never move it out. This happens for all machines that have smaller quantity than size of the truck. We will be reworking priorities and hopefully cover this case.

**Comment by MaFi-Games** [comment] 2021-12-15 21:49
This has been (hopefully) fixed in the upcoming beta patch, thanks for reporting! If you encounter this again in the beta, please report it.

**Closed by MaFi-Games** 2021-12-15 21:49 UTC
Labels: good first issue, bad behavior
