### ISSUE TITLE
Radiation stuck at -0.10%

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#783] opened 2022-09-12 13:09 UTC
### Issue description

All Spent Fuel is being stored but radiation is stuck at -0.10%
![image](https://user-images.githubusercontent.com/108291414/189660718-d0b480d7-8977-46fe-8cb5-c7c54fadaed2.png)

### Expected behavior

No radiation penalty to be present when all spent fuel is stored properly, and if there is spent fuel not being stored properly, a way to tell the player where it is.

### Reproduction steps

1. Load save
2. Check unity tab
3. Check spent fuel storages

### Game version

v0.4.11

### Attachments

[Save Game](https://drive.google.com/file/d/1F1NwVyH_ubSmau0AS1AfJpM6m7uZAj2m/view?usp=sharing)

**Comment by MaFi-Games** [comment] 2022-09-25 19:19
This happens because there is some spent fuel that we track incorrectly. Basically the fuel was destroyed / used in the game but we stilltrack it and giving a penalty for it (considering it exposed). However I don't know how it could happen. But I found one case: collapsing shipyard that has spent fuel in it will cause it. That will be fixed in the next patch. With regards to the state when it already happened, we can't easily retrospectively fix that, unfortunately. Also there is possibility that there is some other way how this can happen but we don't know about it.

**Comment by treeranger** [comment] 2022-09-28 14:40
Thank you for the consideration of my issue and the explanation.  In my case, I never destroyed my shipyard.  I may have moved some of my nuclear storages.  I emptied the storage units as required in the game, I did NOT destroy any storage units or other items in game.  Perhaps this additional information will help MaFi eliminate this issue in the future.  In the meantime, I will hope your future updates will clear out my issue :)

**Comment by treeranger** [comment] 2022-10-17 03:37
Please reevaluate this ticket considering the information documented to date and the following:

1) After 100 or so hours of gameplay the 0.19 radiation persisted 
2) just today I noted 3 spent fuel barrels in a connector.  Other spent items would pass through the connector; however, the contents of the connector stayed at 3.  I tried reconnecting many ways to the connector, reversed directions, etc. however the 3 spent items would NOT leave the connector.  I then deleted the connector in hopes the barrels would go to the dock and the radiation would drop back to 0.19.  However neither happened.  Radiation now stuck at 0.49.  Please help clear these barrels that are causing this radiation issue.  I will post a screen shot.

**Comment by treeranger** [comment] 2022-10-17 03:56
![download jpeg-1](https://user-images.githubusercontent.com/53916950/196086020-9ade7423-b998-4148-9fa6-7a059e86e7a3.jpg)
![download jpeg](https://user-images.githubusercontent.com/53916950/196086025-4039aef2-0d67-4c37-94d0-abb6d955fe6a.jpg)

**Comment by treeranger** [comment] 2022-10-17 05:10
Please note, I also saved a copy of the saved game with the connector holding on to the spent fuel.  If helpful I can forward a copy of the file.

**Comment by zuff-coi** [comment] 2022-10-17 13:33
> Please note, I also saved a copy of the saved game with the connector holding on to the spent fuel. If helpful I can forward a copy of the file.

I would provide a copy of the save file, just to be safe!

**Comment by treeranger** [comment] 2022-10-17 16:03
The save file is 36 MB and there is a limit of 25 MB.  I will forward to Zuff via email.

**Comment by treeranger** [comment] 2022-10-20 20:31
My game file with the new radiation issue,documented in this ticket, was sent to Zuff.

**Comment by zuff-coi** [comment] 2022-10-20 21:05
Thanks @treeranger we'll take a look at it. Thanks for sending it out!

**Comment by treeranger** [comment] 2022-11-08 18:15
The issue with fuel waste getting "stuck" inside connector has happened again.  Would you like a copy of this file too?  It is the same map as before HOWEVER, the location of the issue is different.  It is also perhaps 40+ hours of more game play since the last save.  This issue and this location is of serious concern because I know if I delete the connector with the stuck fuel waste, it will "lose" the waste and add even more permanent background radiation.  This is a serious problem and I don't want to stop using this map.  I cannot go back to an old save because I missed the issue and have play perhaps 20+ since I last check for issues.

**Comment by treeranger** [comment] 2022-11-08 18:49
I just got another one.  This one has 3.  My permanent radiation
![Screenshot 2022-11-08 134747](https://user-images.githubusercontent.com/53916950/200650044-1fe841a9-e6be-46e3-8e5d-30a8c87fc3ac.png)
 is now higher.  I have to use 2 unity just to get population net positive.

**Comment by MaFi-Games** [comment] 2022-11-28 21:07
We have found another issue. Anytime you delete a connector that contains spent fuel, that fuel will forever count as leaked one. We will fix this in the next patch. Unfortunately we are unable to revert the radiation penalty globally. The only option is that I can manually fix your save file once v0.4.13 is out.

**Comment by zuff-coi** [comment] 2022-12-23 18:05
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.

**Comment by MaFi-Games** [comment] 2022-12-28 19:26
Please send us your save file to support@captain-of-industry.com if you'd like us to fix the radiaton issue.

**Comment by treeranger** [comment] 2022-12-28 22:33
> Please send us your save file to [support@captain-of-industry.com](mailto:support@captain-of-industry.com) if you'd like us to fix the radiaton issue.

Thank you very much!  I will do that for sure.  I'm playing most days while on vacation and don't want to be without the master file an entire day :).  I'll send next week OR I could send this week at night.  I'm GMT-5 so you might all be able to fix it before I get "online" around 1200 PM GMT -5.

I appreciate your support and product very much.  Thank you again!

**Comment by treeranger** [comment] 2023-01-05 17:39
> Please send us your save file to [support@captain-of-industry.com](mailto:support@captain-of-industry.com) if you'd like us to fix the radiation issue.

I sent an email to support@captain-of-industry.com with a link to the master file.  Many thanks again!

**Closed** 2023-02-04 17:30 UTC
Labels: bad behavior
