### ISSUE TITLE
Truck assigned to storage remains parked beside storage

### ISSUE THREAD

**Issue by mmikeyy** [MaFi-Games/Captain-of-Industry-issues#417] opened 2022-06-23 02:27 UTC
assign a truck to a storage. The truck moves to the storage and parks itself next to it and does nothing.

 The storage is empty. I assigned an import route to the mine (not that I really had to). Other trucks go back and forth between mine and storage to fill it. Only the assigned truck remains idle. See attached screenshot. A is the idle assigned truck. B is another random truck that took it upon itself to fill the storage while the assigned truck is doing nothing. Is this normal??
![lazy assigned truck](https://user-images.githubusercontent.com/1971024/175193880-c36f83b3-13e6-4862-aa0d-97d81d4bc021.png)
?

**Comment by MrJoshua023** [comment] 2022-06-24 01:20
Sounds related to the issue I reported here as well.  It's not using the assigned trucks first.  I might guess it's using the "closest" available truck to the pick up.  So unless your trucks get busy, the assigned one just sits there.

https://github.com/MaFi-Games/Captain-of-Industry-issues/issues/421

**Comment by utdrmac** [comment] 2022-06-24 01:36
Duplicate of #406

**Comment by MaFi-Games** [comment] 2022-06-27 17:54
duplicate of #406

**Closed** 2022-06-27 17:55 UTC

**Comment by MaFi-Games** [comment] 2022-06-27 17:56
Duplicate of #406
