### ISSUE TITLE
underground pipe destroys when a pipe is built on top of it

### ISSUE THREAD

**Issue by MrErglis** [MaFi-Games/Captain-of-Industry-issues#548] opened 2022-07-10 19:08 UTC
### Issue description

pipes  build under level -1 and -2   after  covering with a materials    they are self distraction  if you build lvl +1 and +2  pipes top of them.     traying  to manage  big pipe working and its not working.  but  same thing  but top off conveyer  belt  its works nicely.

### Expected behavior

so I traying understand  if there is a limits how deep can go  and then  put on top of it   because is now  -2 -1  pipes 0 +1  can set up broking lower pi
![Untitled](https://user-images.githubusercontent.com/109040232/178158593-a075b57e-7068-4749-bd07-387343879cd7.jpg)
pes +2+3 is okay for them    all i wanted  to do is pipes -1  and+1 pipes

### Game version

v0.4.7d

### Attachments

![Untitled](https://user-images.githubusercontent.com/109040232/178158604-4120fba2-81eb-4248-81a7-8db58cb61870.jpg)

**Comment by MrErglis** [comment] 2022-07-10 19:33
![Uploading Untitled.png…]()

**Comment by ParanoikCZE** [comment] 2022-07-10 21:14
Afaik this is known and building on top of buried stuff is not supported or at least not stable.

**Comment by MrErglis** [comment] 2022-07-11 05:11
I see. But way it's works on conveyier?

**Comment by BainrowKiss** [comment] 2022-07-28 10:41
#355  ?

**Comment by zuff-coi** [comment] 2022-08-20 15:58
Duplicate of #355

**Closed by zuff-coi** 2022-08-20 15:58 UTC
Labels: duplicate, bad behavior
