### ISSUE TITLE
Conveyor Feed Failure

### ISSUE THREAD

**Issue by theargyll** [MaFi-Games/Captain-of-Industry-issues#226] opened 2022-06-05 22:53 UTC
**Describe the issue**
Newly placed (within last 30 minutes, as at 2350 GMT; 5th June 2022) conveyors when attached to storage, balances or conveyor junctions refuse to feed cargo.  Previously placed examples of the above still work.

**Expected behavior**
Feeds to perform per design.

**To Reproduce**
a) Load Save
b) Place storage.
c) Attach conveyor (I or II)
d) No feed.

**Additional context**
 - Game version: 0.4.1E
[Save Game.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8840921/Save.Game.zip)

**Attachments**
Save game attached

**Comment by theargyll** [comment] 2022-06-06 06:50
![22-06-06_07-48-17_6463_photo](https://user-images.githubusercontent.com/106934569/172110276-2e73a287-2d17-4bda-b163-c1bbc3a2dc20.jpg)
Example screenshot (belts 1, 2 and 3 from left cease feeding cargo after splitter)

**Comment by MaFi-Games** [comment] 2022-06-15 11:04
Sorry but I'm not sure what is the issue there. On the screenshot it seems that things are being supplied properly. And in the save file provided, I can't seem to find this setup anywhere.

**Comment by PTTG-ACTUAL** [comment] 2022-08-06 01:21
I've encountered what may be a similar issue. Save camera is set up directly over a new set of belts which aren't being fed by the splitters. Is it possibly related to building with snapping disabled?

![image](https://user-images.githubusercontent.com/74290971/183227863-120c395a-bbb8-4050-a5a8-f6c87c769f0e.png)
[YSNP Megopolous f.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9274180/YSNP.Megopolous.f.zip)

Oh, very interesting... loading the save causes the issue to go away instantly. Will continue pursuing.

**Comment by MaFi-Games** [comment] 2022-11-25 14:39
We will close this as there is no other report like this and it seems we can't reproduce.

**Closed by MaFi-Games** 2022-11-25 14:39 UTC
Labels: could not reproduce, need save file or exact repro steps
