### ISSUE TITLE
Broken save games

### ISSUE THREAD

**Issue by DIGITDUDE** [MaFi-Games/Captain-of-Industry-issues#504] opened 2022-07-04 17:04 UTC
**Describe the issue**
my save games keep breaking, when i try to load the next time i play ta error come around after a minute orso of loading screen.

**Expected behavior**
expect to load my save game
[broken save games.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9041177/broken.save.games.zip)

**To Reproduce**
[broken save games.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9041157/broken.save.games.zip)

1. Load attached save(one of them they are all broken) or click continue game with one of the saves
2. wait the loading screen
3. after a minute or so, and the loading bar goes on till 1/6 of the bar until an error pops up with a lot of text.( i cant copy out of the error)

**Additional context**
 - Game version: 0.4.7a
 - installed two days before patch 0.4.7

**Attachments**
Broken save  games .zip

**Comment by MaFi-Games** [comment] 2022-07-04 22:00
Duplicate of  #453

**Comment by MaFi-Games** [comment] 2022-07-04 22:00
Duplicate of #453

**Comment by MaFi-Games** [comment] 2022-07-04 23:48
This has been fixed in `v0.4.7b`, thanks for the report.

**Closed by MaFi-Games** 2022-07-04 23:48 UTC
