### ISSUE TITLE
Population text alignment issue

### ISSUE THREAD

**Issue by utdrmac** [MaFi-Games/Captain-of-Industry-issues#561] opened 2022-07-13 02:41 UTC
### Issue description

See attached screenshot. Icons/numbers are not bottom aligned and the spacing is inconsistent.

### Expected behavior

Icons and numbers to be aligned :)

### Game version

v0.4.7.d

### Attachments

![image](https://user-images.githubusercontent.com/4413670/178639366-af4f56c7-d288-483c-852b-b950a3047b7b.png)

**Comment by MaFi-Games** [comment] 2022-11-25 18:01
Cannot reproduce. Was probably fixed? If not, please provide your resolution & UI scaling settings.

**Comment by MaFi-Games** [comment] 2023-08-03 13:21
Closing as not reproducible for now.

**Closed by MaFi-Games** 2023-08-03 13:21 UTC
Labels: could not reproduce, user iterface
