### ISSUE TITLE
Trucks ignoring P2 export request

### ISSUE THREAD

**Issue by mnoreke** [MaFi-Games/Captain-of-Industry-issues#398] opened 2022-06-21 13:00 UTC
**Describe the issue**
My city trash is set to P2 and is overflowing. Trucks are running other jobs instead of the highest priority I have set.

**Expected behavior**
Treash to be emptied from the storage in town.

**To Reproduce**
1. Load attached save [P2 ignored for trash.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8949057/P2.ignored.for.trash.zip)
2. Watch the storage outside town be ignored

**Additional context**
 - Game version: 0.4.5a

**Attachments**
Save file is attached

**Comment by utdrmac** [comment] 2022-06-22 03:09
I found this to be true as well with the recent 0.4.5 update. I believe the issue is that if the mine control tower(s) that accept waste are linked from other sources, then the trucks believe there is nowhere to dump waste. You cannot link the housing waste building to a mine tower. I solved this issue by making a storage bucket nearby and belting the waste into the bucket. Then I linked this bucket to the tower and trucks started taking trash again out of the bucket.

**Comment by zuff-coi** [comment] 2022-12-23 18:12
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.

**Closed by zuff-coi** 2022-12-23 18:12 UTC
Labels: fixed in v0.4.13

**Comment by laskiewicz** [comment] 2023-06-08 19:06
I can confirm that this issue is still present in 0.5.1b

I have storage with rocks set to empty with priority at 15. Trucks keep exporting rocks even though plenty of unfinished jobs across the island exist.
