### ISSUE TITLE
Purple waste bin in a Smoke Stack blueprint

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#806] opened 2022-09-19 06:51 UTC
### Issue description

Minor bug, but still ...
![FlareBin](https://user-images.githubusercontent.com/109154186/190964697-51c20507-883c-4408-b210-a55148beb42d.jpg)
![SmokeBin](https://user-images.githubusercontent.com/109154186/190961562-2a76b859-e4bc-41c9-b052-8f30c07904cd.jpg)

When you pay Unity, all purple waste bins disappear ... in all affected blue prints.
After that, they will not show up anymore. You have to reload a savegame to see it again.

At least Flare, small & large Smoke Stack are affected.

### Expected behavior

I think we can agree, that never ever the (otherwise useful) purple waste bin may show up in a blueprint. As a blueprint can't have any production leftovers.

As a SW developer and tester I wonder what went wrong there ... esp. as the smoke stacks show the bin only on two recipes.

### Reproduction steps

In the blueprint, I unset all recipes.

### Game version

v0.4.12a

**Comment by zuff-coi** [comment] 2022-09-20 14:51
Can't reproduce this exactly but I noticed that turning off a recipe in the smoke stack doesn't stop the product from being brought in and constantly refills after clicking the Trash icon (which isn't disappearing for me)

**Comment by RealisticOptimist** [comment] 2022-09-20 14:54
I saw it on a blueprint/ghost, not a on a built one!
Just a ghost pipe was connected, definitely no products in there.
What you describe might be another issue. It should not accept more after turning off.

**Comment by MaFi-Games** [comment] 2022-09-21 13:51
I don't seem to be able to reproduce this issue. When I place a smoke stack or a flare and unselect their recipes, I don't see the bin icon. Would you have a save file that reporoduces it or specific repro steps?

**Comment by RealisticOptimist** [comment] 2022-09-22 00:25
Hm, I can confirm it does not seem to occur on a new virgin map. 
But already on the attached save I see it. It even survives save/load.

[SmokeBin.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9621147/SmokeBin.zip)

![SmokeBin](https://user-images.githubusercontent.com/109154186/191632369-f47bd24e-c0d9-4873-863a-24f42eaa90ae.jpg)

**Comment by MaFi-Games** [comment] 2022-09-25 19:14
You have actually managed to find a fairly tricky case which is actually fairly important to fix. Will land in the next patch. Thanks!

**Comment by zuff-coi** [comment] 2022-12-23 16:54
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.

**Closed by zuff-coi** 2022-12-23 16:54 UTC
Labels: bad behavior, user iterface, fixed in v0.4.13
