### ISSUE TITLE
Upgrade cost of Blast Furnace is inconsistent

### ISSUE THREAD

**Issue by Baconchsbrgr** [MaFi-Games/Captain-of-Industry-issues#411] opened 2022-06-22 13:15 UTC
**Describe the issue**
When attempting to upgrade blast furnaces from I to II, some upgrade costs are 180 Construction III parts while other Blast Furnaces cost 540 Construction III parts.

**Expected behavior**
Price upgrades for all Blast Furnaces from I to II is expected to be the same.

**Steps to reproduce the behavior:**
-Load attached save.
-Check upgrade costs for Blast Furnaces (level I) IVO Iron Mine and Copper Mine. 
-Costs to upgrade are different depending on Blast Furnace selected.

**Additional context**
-Several of these Blast Furnaces were made at different points in the game update timeline; older Blast Furnaces _appear_ to have the higher upgrade cost, though I cannot prove this statement and therefore it is conjecture. It may be that certain furnaces were built prior to a specific game update.
-Attached png file also shows images of two Blast Furnaces and their associated upgrade costs when hovering over the "upgrade" button.
Game version: 0.4.5B
![Blast Furnace Upgrade Bug](https://user-images.githubusercontent.com/108004172/175036208-8b69156f-494e-4388-a1d4-ce73a0d521cd.png)
[Beach Build.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8957887/Beach.Build.zip)

**Comment by MaFi-Games** [comment] 2022-06-23 09:06
Duplicate of #309

**Closed by MaFi-Games** 2022-06-23 09:06 UTC
