### ISSUE TITLE
Trucks Appear to be overloaded

### ISSUE THREAD

**Issue by rparty0516** [MaFi-Games/Captain-of-Industry-issues#525] opened 2022-07-07 10:38 UTC
### Issue description

My trucks have stopped working well in my game, it seems like only a certain number of trucks are able to complete a task at one time. I can watch as a truck will come and dump something in a dumping zone and then freeze, while a truck that was frozen will then start to take on a new task.

 I am running a windows 10 machine, Intel Xeon W-2225 @ 4.10 GHZ, 32 GB Ram, NVIDIA Quadro RTX 4000 video card.

### Expected behavior

All of the trucks should run at the same time

### Reproduction steps

Load the trucks broken save and look at the map, if you are looking at the main ship dock from the ship side, there will be a bunch of stuck trucks over on the right hand side of the island.

### Game version

V0.4.7D

### Attachments

[Trucks Broken.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9062743/Trucks.Broken.zip)

**Comment by ParanoikCZE** [comment] 2022-07-07 22:25
Possibly duplicate of #474

**Closed** 2022-07-12 17:00 UTC

**Comment by zuff-coi** [comment] 2022-07-29 14:51
We [released an update on the experimental branch](https://steamcommunity.com/games/1594320/announcements/detail/4972554042131344663) which has fixes aimed at this issue. If you could please try it out and let us know if your issue is resolved that would be great!
