### ISSUE TITLE
Entire refinery replaced by trash?

### ISSUE THREAD

**Issue by screaney** [MaFi-Games/Captain-of-Industry-issues#1062] opened 2023-06-05 17:19 UTC
I noticed that my excavators and trucks started having issues with simple pathfinding.  Couldn't find routes even though they should've been valid (like a 1 height ramp).  Then, noticed by entire refinery had been replaced by piles of trash? I honestly have no idea what I'm looking at here.  In the screenshot you can see the outlines of what WERE building and pipes, but now it seems to be just piles of trash.

![20230605114613_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/29961829/9d5f2079-7b7e-45ee-82f1-30ca3091f5e5)

**Comment by MaFi-Games** [comment] 2023-06-05 17:20
Can you please provide a save before and after this happened so we can investigate?

**Comment by screaney** [comment] 2023-06-05 17:23
![20230605122013_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/29961829/e161fb28-deef-4fd6-a943-5071d7e81751)
Also adding a screenshot showing that the truck that should be able to route cannot.
[Bug.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11655092/Bug.zip)
[before.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11655111/before.zip)


Including saves.

**Comment by MaFi-Games** [comment] 2023-06-05 19:38
Thanks for the save. The issue is water that spread from a hidden pool. We will try to fix this to but to avoid this issue until then, please dump this water pool with material before you start mining near it.

![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/90082857/a84a759e-5570-4b8e-a845-6f6e5847629a)

**Comment by screaney** [comment] 2023-06-05 19:59
Does that explain why the truck could not route to this lower area? because it was considered 'flooded'?

**Comment by MaFi-Games** [comment] 2023-06-07 03:34
Yes, exactly. This has been fixed in v0.5.1b by making sure that the water is more visible on height 0.

**Closed by MaFi-Games** 2023-06-07 03:34 UTC
