### ISSUE TITLE
Recipes not available in 0.4.10

### ISSUE THREAD

**Issue by ksorbo** [MaFi-Games/Captain-of-Industry-issues#727] opened 2022-08-17 17:14 UTC
### Issue description

When I click the recipe button on the far right left, nothing happens.

If I click just a little toward the top of the icon, the Statistics panel opens.

This was not the case in the previous release (0.4.9c)

### Expected behavior

Expect the recipe panel to open

### Game version

v.0.4.10

**Comment by ksorbo** [comment] 2022-08-17 17:21
This apparently only happens in windowed mode. If I go to full screen, everything works as expected

**Comment by zuff-coi** [comment] 2022-08-17 17:58
Duplicate of #667

**Closed** 2022-08-20 12:50 UTC
Labels: duplicate, user iterface
