### ISSUE TITLE
Save files in different locations between computers, causing Steam Cloud to not work properly

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#808] opened 2022-09-19 13:06 UTC
### Issue description

[0skymaster0](https://steamcommunity.com/profiles/76561198025959062) is having issues on the [Steam Forums](https://steamcommunity.com/app/1594320/discussions/2/3437955554614359231/) with Steam Cloud Sync:

On my laptop the game installed itself automatically saved to the following location:

`C:\Users\Myname\Documents\Captain of Industry\Saves`

On my gaming PC the game installed itself automatically saved to the following location:

`C:\Program Files (x86)\Steam\steamapps\common\Captain of Industry\Captain of Industry\Saves`

I tried deleting, re-installing, manually syncing. If I copy the file manually to the PC location from the Laptop the game will not start either...

No I don't run ransonware protection on either computer.

### Expected behavior

Saves to be synced properly between machines

### Game version

v0.4.12

**Comment by RealisticOptimist** [comment] 2022-09-19 23:05
Isn't this same as #775?

On my PC I get the Steam Cloud Sync error sporadically, too. But I do not have saves in the Steam path, all are in my Documents path.

**Comment by MaFi-Games** [comment] 2022-11-26 17:45
Duplicate of #896

**Closed by MaFi-Games** 2022-11-26 17:45 UTC
Labels: bug
