### ISSUE TITLE
Trucks sometimes get into places they shouldn't be able to

### ISSUE THREAD

**Issue by lowstrife** [MaFi-Games/Captain-of-Industry-issues#208] opened 2022-06-05 06:47 UTC
About once an hour with 60 trucks, one of them will randomly somehow make it's way into a completely enclosed area. 

The belts in this picture have not been modified or touched for hours, but somehow this truck just showed up there. It's close, but not within range, of a warehouse it could have tried to make a delivery to. But the warehouse is on the other side of 2 assemblers. I'm not sure why it was there, nor how it got through the belt.

![image](https://user-images.githubusercontent.com/65734844/172038936-b7b4ed97-be73-4115-a352-5cb4d572c4cc.png)

[Stuck truck.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8839449/Stuck.truck.zip)

(side note: this log file may not be up to date - it's last_modified timestamp is about 15 minutes before this issue happened. But here it is anyway)

[22-06-03_12-19-09_7926.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8839450/22-06-03_12-19-09_7926.log)

**Comment by JamieRCHI** [comment] 2022-06-05 16:11
I haven't seen this, but I have seen trucks get stuck when there is nothing blocking them.

**Comment by camtarn** [comment] 2022-06-12 18:46
Yeah, I've had maybe 10-15 instances of trucks doing this. It's not particularly annoying as you can just pay unity to get them out, but it's definitely weird!

**Comment by TH3xR34P3R** [comment] 2022-06-22 06:38
![IYeNNNdWq1](https://user-images.githubusercontent.com/5105021/174960006-f76b4d58-cf71-473c-b8b6-22a69d4faaaf.png)

Trucks are ignoring this part of the bollard when driving around, they drive through it and earlier I had a truck somehow get stuck inside after it was setup to prevent this issue.

![Captain_of_Industry_1cFmxVlfsk](https://user-images.githubusercontent.com/5105021/174960263-ce979e49-d05c-44c7-b803-f57bfab286ae.jpg)

**Comment by JamieRCHI** [comment] 2022-06-22 14:19
I have seen this a lot. They will also drive over corners of the retaining walls.

**Comment by MaFi-Games** [comment] 2022-11-26 17:52
Duplicate of #338

**Closed by MaFi-Games** 2022-11-26 17:52 UTC
Labels: bad behavior
