### ISSUE TITLE
Assembly Electric II only produces two units of lab Equipment II

### ISSUE THREAD

**Issue by Redpossum** [MaFi-Games/Captain-of-Industry-issues#299] opened 2022-06-11 01:03 UTC
Assembly Electric II only produces two units of lab Equipment II rather than the 4 it is supposed to.

I expected the process to produce four (4) units of Lab equipment II like the recipe says.

Just set it up and run the process

game version Early Access 0.4.3

**Attachments**
screenshot attached, savegame attached, zipped per your request. You'll find the offending Assembly Electric II building connected to the Research Labs by a conveyor, should be obvious.

If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.
![onlt two units](https://user-images.githubusercontent.com/46661851/173166414-7fcdcd5b-846a-4fc5-a6ed-5cdc4202fabf.jpg)
[captain savegame.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8882841/captain.savegame.zip)

**Comment by utdrmac** [comment] 2022-06-12 01:52
Working fine over here. 0.4.3. I just upgraded this a few hours ago and all has been fine.

![image](https://user-images.githubusercontent.com/4413670/173210856-810a58b8-dfae-4c30-bef0-a617c87d9397.png)

**Comment by MaFi-Games** [comment] 2022-11-25 15:08
Duplicate of #531

**Closed by MaFi-Games** 2022-11-25 15:08 UTC
