### ISSUE TITLE
Dumping/Mining designations not going away

### ISSUE THREAD

**Issue by Memnoch72** [MaFi-Games/Captain-of-Industry-issues#624] opened 2022-07-25 23:44 UTC
### Issue description

This has only happened once to me so far, but I was in mining designation mode, added quite a few designations, and also removed and re-added some without going out of the overlay.  I clicked on the mining tower to designate a new area, and when I did so, the mining designations overlay didn't go away.  It didn't matter what I went into, or clicking M or Z to get in/out of the modes, but the overlay were showing all the time.

The other odd thing at the time is that the icon for Cut [X] in the lower left hand corner of the screen was lit up, even though I wasn't in cut mode.

I haven't been able to recreate it, I saved the game and reloaded and it went away.  Don't think I could recreate it.

### Expected behavior

N/A

### Reproduction steps

Unable to reproduce, see notes in comments

### Game version

v0.4.8

**Comment by MaFi-Games** [comment] 2022-08-20 14:03
Closing as can't reproduce. Please let us know if you have more repro details.

**Closed by MaFi-Games** 2022-08-20 14:03 UTC
Labels: could not reproduce
