### ISSUE TITLE
Moving camera with right click of sharp inclines causes snapping.

### ISSUE THREAD

**Issue by Burnrate** [MaFi-Games/Captain-of-Industry-issues#45] opened 2021-10-05 14:47 UTC
**Describe the issue**
When moving the camera by hold right click, if the cursor location moves over a sudden change in depth such as a deep hole the camera position will snap back and forth rapidly.

**To Reproduce**
1. Load attached save '...'
2. Right click with the curser near the edge of a hole and move the camera.
3. 

**Expected behavior**
The right click camera movement should be based only on the mouse screen location on not something else (world position idk?).  It should give smooth movement.

**Additional context**
 - Game version: Alpha 0.2.10a

**Attachments**
Save file and screenshot of good location to try it out
![br1](https://user-images.githubusercontent.com/2849955/136046226-cb742faf-6b9b-4b99-9f0f-758020148fca.jpg)

[G2 - THIS IS THE SAVE FILE.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7286806/G2.-.THIS.IS.THE.SAVE.FILE.log)

**Comment by MaFi-Games** [comment] 2021-12-15 07:44
Mouse panning and terrain height changes do not play well, we need to work on this. Thanks for reporting.

**Comment by MaFi-Games** [comment] 2022-11-25 17:51
Duplicate of #438

**Closed by MaFi-Games** 2022-11-25 17:51 UTC
Labels: bad behavior, beta issue
