### ISSUE TITLE
Trucks "ignore" red field of navigation overlay

### ISSUE THREAD

**Issue by Blottoo123** [MaFi-Games/Captain-of-Industry-issues#133] opened 2022-01-27 00:41 UTC
**Describe the issue**
Trucks usually driver over the red fields of navigation overview, see picture "Screen Driving Over Red Marked Field". And sometime they take corners to wide or to close and ended up on a green spot surrounded bey red (do not cross) fields. Sometimes when they take the corner to wide they have to turn around and start a new try to take the ramp. It´s also a bit funny to watch them.
I saw the issue also in a earlier game after beta launch, but nothing documented.

**To Reproduce**

1. See picture "Screen Truck Stuck"
2. Load attached save "Blottoo Golden Peak Beta Truck Stuck"
3. Let the game run for maybe 30min. There was another Truck which stuck at the same place after that time.

Or try the setup of ramps to force the truck to get stuck. I had a setup like this in my last game and the trucks stuck often there.

1. See picture "Screen Force Truck To Stuck"
2. Load attached save "Ramp To Force Truck Stuck"
3. Just let run. 

**Expected behavior**
The Trucks stuck on a green spot surrounded by red field.

**Additional context**
 - Game version: 14 day´s after beta launch until now 0.3.11f

**Attachments**
2 Save Files
3 Screenshots
[Blottoo Golden Peak Beta Truck Stuck.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7946606/Blottoo.Golden.Peak.Beta.Truck.Stuck.zip)

**Comment by MaFi-Games** [comment] 2022-11-26 17:52
Duplicate of #338

**Closed by MaFi-Games** 2022-11-26 17:52 UTC
Labels: beta issue
