### ISSUE TITLE
Lost Savegames

### ISSUE THREAD

**Issue by Jappy176** [MaFi-Games/Captain-of-Industry-issues#252] opened 2022-06-07 20:29 UTC
Missing Savegames

I`ve started the Game first time 3 days ago and played for about 2hours then i saved the game manuelly, next day i started the game again and my savegame was not to find in the loadingmenu. I tried to start a new Game and it works it saved after i stopped playing. 
on the third day my last save from the second day was gone und my saves from the first day showed up so i started one of them, everything ok, they started perfectly. Now on the third day the savegame that i created yesterday, after the saves from the first day were gone, showed up.
**Expected behavior**
Explain what you expected to happen.

**Additional context**
 - Game version: Early Accsses Version 0.4.1E

Sorry but i`m unable to show you what happen but i can`t show you what isn`t there

Yours
Jappy

**Comment by Jappy176** [comment] 2022-06-10 21:09
The Problem is, i see the last Saves inclusive the automatic saves on my pc, in the Folder. But in the Game, it shows me somthing, i can find somewere. and i`m tried your method but it want work. Take a look please. In the first Picture you will see what the Game want tell me in the second one it is what my Steamfolder show
![Screenshot 2022-06-10 230440](https://user-images.githubusercontent.com/107076769/173151455-ca316042-ff1c-4816-8291-0db15f5dadb7.png)
![Screenshot 2022-06-10 230606](https://user-images.githubusercontent.com/107076769/173151475-c0f57443-05e1-4264-85cc-82008f5f359d.png)
s

**Comment by MaFi-Games** [comment] 2022-06-16 23:36
@Jappy176 When this happens again, could you share you COI logs AND Steam logs? Our logs are at `%userprofile%\Documents\Captain Of Industry\Logs` and Steam logs are located in `Program Files (x86)\Steam\logs` (you can zip all the files there). This would help us determine whether this is issue with Steam or with our game. Thanks!

**Comment by Jappy176** [comment] 2022-06-17 00:20
Hello I think i found the problem tere are two destinations who the Game saves, one is in the Windows directory and the other is in the steam library wich is on an other ssd on my desk. Unfortunately i`ve experimented with the saves, so i can`t send you so much data if you need.
[logs from Drive C.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8923494/logs.from.Drive.C.zip)
[Steamlogs.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8923506/Steamlogs.zip)
 Ihope this will help you to fix the problem.
tere are two thinks that i want to show in the pictures who are here to
![Screenshot 2022-06-17 021815](https://user-images.githubusercontent.com/107076769/174198540-a115e571-6a50-4d5d-9f29-4db824366227.png)
![Screenshot 2022-06-17 021941](https://user-images.githubusercontent.com/107076769/174198559-119cefa8-a9bd-4c9a-b501-04b7c2e60b36.png)
o

**Comment by MaFi-Games** [comment] 2022-11-26 17:44
Duplicate of #896

**Closed by MaFi-Games** 2022-11-26 17:44 UTC
