### ISSUE TITLE
Alert system not working correctly

### ISSUE THREAD

**Issue by ladyzowy** [MaFi-Games/Captain-of-Industry-issues#680] opened 2022-08-06 15:03 UTC
### Issue description

I have many alerts.

When I click on an alert to focus the POI (Point of Interst) it will sometimes bring me to a different POI or close the alert. 

When I attempt to close an alert, it will close a differnt one, or close them all. I'm unable to reopen the list of alerts by using the bell 

The only way I've been able to get the list back is to save and reload the save. I do not need to reload the game or close it before this. 

I'm running in windowed mode. 1920 x 1080

### Expected behavior

Alerts should be viewable and focus the correct POI and also be able to close those alerts. And reopen the alert list by clicking on the Bell in the upper right corner. 

### Reproduction steps

1. click on any alert anywhere in the list. POI not focused or alert will be closed
2. x on the alert line and another item will close leaving the alert I clicked opened. 
3. click on one or more in sessesion or will close the full list. 
4. clicking the bell will not show the list after its been close. 
5. after the list is closed, new alerts will not show. 

### Game version

v0.4.9c

### Attachments

[AutosaveBackupAndScreenShots.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9275277/AutosaveBackupAndScreenShots.zip)

**Comment by ladyzowy** [comment] 2022-08-06 17:06
I've determined that the click is off by a full line. If I click below the bell it shows the list if I click on the bell nothing happens. Its as if the visual and the interaction dont line up. 

My dialogue boxes also don't line up with the screen... they open off screen. And I have to drag them into the screen to see them.

**Comment by zuff-coi** [comment] 2022-08-08 14:50
Duplicate of #667

**Comment by MaFi-Games** [comment] 2022-08-21 22:39
Closing as duplicate. Please track 667 for resolution.

**Closed by MaFi-Games** 2022-08-21 22:39 UTC
Labels: duplicate, user iterface, needs investigation
