### ISSUE TITLE
Loading saved game - default location changes and no way to override 

### ISSUE THREAD

**Issue by Andysimcoe** [MaFi-Games/Captain-of-Industry-issues#887] opened 2022-11-02 09:13 UTC
### Issue description

The location the game looks for saved files switches between 2 locations, doesn't appear to be a way to switch the location so you're forced to restart the game and hope it picks up the location you have your saves. 

Originally they are in:
C:\Users\<user>\Documents\Captain of Industry\Saves

But sometimes it changes to:
E:\<Steam files location>\steamapps\common\Captain of Industry\Saves

The second location doesn't actually exist (at least Saves doesn't). 

### Expected behavior

I would expect it to keep the same location each time the game is started and for the 'SHOW IN FOLDER' button to allow me to select a different location or allow me to edit the location. 

### Reproduction steps

1. Start game
2. Continue has no previous game
3. Click Load
4. No previous saves
5. Restart game and it's back to the previous location

### Game version

0.4.12E

**Comment by MaFi-Games** [comment] 2022-11-26 17:45
Duplicate of #896

**Closed by MaFi-Games** 2022-11-26 17:45 UTC
