### ISSUE TITLE
Performances issue: Upgrading the greenhouses

### ISSUE THREAD

**Issue by McRib33** [MaFi-Games/Captain-of-Industry-issues#349] opened 2022-06-15 14:29 UTC
hi Marek and Filip,

i found a performances issue that can decrease the game performances in one case: 

The issue is that when you start upgrading your farms to greenhouses it cost it slow tremanously the performance down the game. However it is not really link to the GPU drain need that only go up to 20% more but stay under 50% however (normaly around 20-30%) the game start to lag. I made a save game to show you this issues. (when the upgrading start please slow down to 1x speed and have the farms in view to show the issue.

I hope that help you finding a performances drain (even it is only for one case).

The GPU i use is GTX 2070 Super Gigabyte so it is not up to date but still it should play most games on highest settings show this kind of stuttering on a WQHD screen (and it doesnt normaly)

I hope you find the cause of it. I made this save game for this issue so to make the issue more clear i start upgrading every farm and have the neessary materials at hand. Please keep the camera on the farms and wait until 3-4 of them start to upgrade at ones than slow down to 1x speed and move the camera around you will notices the game is lagging.

[Performances issue.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8910261/Performances.issue.zip)

**Comment by empty-quiver** [comment] 2022-06-15 17:54
Would like to add to this, I also have the same issue where my FPS gets hit tremendously when I have the camera viewing any greenhouse upgrade. It seems to get worse and worse as the little green construction blocks envelop the building during the upgrade, and then the problem is gone when the upgrade finishes. I have an RTX 3060 and play the game with a 1080p monitor, I usually get between 30 and 60 FPS, it drops to about 10 during this issue.

**Comment by daltay15** [comment] 2022-06-16 05:23
The same thing happens with me.

**Comment by Stalkie** [comment] 2022-06-20 18:54
Same for most large building scaffolding animation it seems. For me i get down to 18 FPS while upgrading the Tomb.
Running on RTX 3080 | Ryzen 5600x
![bild](https://user-images.githubusercontent.com/26777760/174663198-e0aed47b-91d0-477a-8db1-8b0df3b68649.png)

**Comment by MaFi-Games** [comment] 2022-11-24 15:43
Thanks for report. This was fixed in our last performance update.

**Closed by MaFi-Games** 2022-11-24 15:43 UTC
