### ISSUE TITLE
Water inconsistency (unexpected flooding)

### ISSUE THREAD

**Issue by Frankkasza** [MaFi-Games/Captain-of-Industry-issues#293] opened 2022-06-10 17:30 UTC
**Describe the issue**
Inconsistency with the watermodel as the ocean floods a well surrounded (at least 8 mining-tiles/64pipewidths from the ocean) pit that shouldn't experience this. I first thought it's the waste and slag are being porous, but they aren't creating a channel when the flooding happens.

**Expected behavior**
The pit should not to flood, have a look on Water3 save and unless there is a hardcoded ocean-border that recreates itself when dug up again there is no way the water logically could get in, there are no holes in the walls.

**To Reproduce**, Water2
Saves: Waterbug, Water1, Water2 are getting closer to the bug, Water2 it's about to, Water3 is when it already happened. Waterinconsistency save is when I took Waterbug save and played around to see if digging into the slag/waste mix creates this, but the depths at which flooding occurs is different between spots (they were dug till they flooded) and they're much closer to the ocean when it pops through.

**Additional context**
 - Game version: 4.2.A

**Attachments**

[Waterbug.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8880831/Waterbug.zip)

**Comment by landie** [comment] 2022-06-19 13:56
I'll just add my save here since it's bad water behaviour related.
**Describe the issue**
My guess is that at one specific point the beach/cliff breakwater gets high enough that it overspills the edge and then the entire section is considered water. Seems like quite the overreaction by the water logic. 

**Expected behavior**
Maybe a warning that a flooding is imminent when mining close too water? Maybe adding the water level to the mining overlay so it's clearer what the boundaries are?

[Flooded mine.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8935608/Flooded.mine.zip)

**Comment by hardkur** [comment] 2022-07-02 02:53
there is a piece of ocean hidden inside rocks , making ground around it move by digging or dumping more on top cause it to flood entire area . it is possible to build wall around it , then trigger the flood , bury it and dig out again solving the issue but its kinda work around as it should not happen in the first place 
![290421949_415935780478114_9034429464029203217_n](https://user-images.githubusercontent.com/5045626/176983999-a786f9e3-308b-4c75-9516-211e09a3aa5d.png)

**Comment by MaFi-Games** [comment] 2022-07-03 04:43
Thanks for the reports, this has been fixed in v0.4.7!

**Closed by MaFi-Games** 2022-07-03 04:43 UTC
Labels: bad behavior
