### ISSUE TITLE
Important issue about missing archive loads ！！！！！

### ISSUE THREAD

**Issue by DXL95** [MaFi-Games/Captain-of-Industry-issues#873] opened 2022-10-17 12:26 UTC
### Issue description

The product has been full of affirmation and support! However, on the morning and noon of Oct 17, 2022, the archive was lost seriously!! (Autosave enabled) cannot be retrieved at present!! A day of hard work down the drain! Unbelievable! Seriously affected my game experience and passion and enthusiasm, I hope the team can make the product more detailed and meticulous! So that customers can still maintain the recognition and trust of the team! Thank you very much!

### Expected behavior

  no  happy

### Reproduction steps

no happy
![Captain of Industry](https://user-images.githubusercontent.com/115994133/196176120-d7c9ac1b-de10-4978-a02e-762508e5a9ca.png)

### Game version

v0.4.12e

### Attachments

no happy

**Comment by MaFi-Games** [comment] 2022-11-22 22:27
I'm not sure how save could disappear, did you by any chance save the game into steamapps/Captain of Industry/Saves?

**Comment by MaFi-Games** [comment] 2022-11-26 23:45
Duplicate of #896

**Closed by MaFi-Games** 2022-11-26 23:45 UTC
Labels: need save file or exact repro steps, potential issue on user side
