### ISSUE TITLE
Resolution setting not persistent

### ISSUE THREAD

**Issue by brucemcook** [MaFi-Games/Captain-of-Industry-issues#155] opened 2022-04-12 18:45 UTC
I use a lower graphics resolution setting to improve fps on my non-gaming computer. Usually this setting is maintained between startups of the game. Sometimes, however, the graphics reverts to the high resolution capability of the computer on startup. The setting UI still shows the desired lower resolution, but it is not the resolution being displayed. To resolve this it is necessary to switch to a different resolution, and then go back to the desired resolution.

**To Reproduce**
There is no clear sequence that causes this behavior. It seems to be random in about one out of ten startups.

**Expected behavior**
The selected display resolution setting should persist between game startups.

**Additional context**
 - Game version: v0.3.11 (it was also seen on earlier beta versions)

**Comment by MaFi-Games** [comment] 2022-11-25 20:32
Duplicate of #669

**Closed by MaFi-Games** 2022-11-25 20:32 UTC
Labels: beta issue
