### ISSUE TITLE
Flat belts issue

### ISSUE THREAD

**Issue by Sharknadohehe** [MaFi-Games/Captain-of-Industry-issues#644] opened 2022-07-30 18:04 UTC
### Issue description

there is a slight issue with the belts thats kinda bothering me

### Expected behavior

so the behavior can only be seen if you pay close attention. so if a product is on the belt and it begins to run the product can back track on the belt and the system picks that up so it slows down the speed by a small fraction but we as captains must solve this issue cause time waits for no man and we must always be moving forward. i have no files you would be able to see it for yourself sorry and  thanks

### Game version

vo.48 newest version

**Comment by zuff-coi** [comment] 2022-08-02 21:18
I could not reproduce this issue. I'll escalate it to the devs. 

A video of what you're talking about could help a lot with describing your report.

**Comment by MaFi-Games** [comment] 2022-11-25 20:26
Closing as not enough information available. We are not aware of belts having throughput issues.

**Closed by MaFi-Games** 2022-11-25 20:26 UTC
Labels: could not reproduce
