### ISSUE TITLE
Visual terrain not updating until pressing ESC

### ISSUE THREAD

**Issue by redshadow3** [MaFi-Games/Captain-of-Industry-issues#1364] opened 2024-02-26 03:16 UTC
### Issue description

i have experienced a bug multiple times, when i turn on my game and load my save, then select a new area for leveling (earlier designated for leveling, im just editing the mine control towers' work area) the terrain will not visually change when the excavators are terraforming, but after i press ESC a few times, it will update and work normally until i load this save again. i have been able to reproduce the bug multiple times

screenshot of my excavators clipping through the glitched terrain:
![Zrzut ekranu 2024-02-26 033830](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/106045016/fe263928-dd08-4d84-b99b-b66a589e3557)

an issue like this has been reported before but closed beacause it wasnt reproduce-able

in advance, sorry for my poor english

### Reproduction steps

1. load attached save
2. edit mining tower area (the one with multiple mega excavators and dump trucks) to terraform pre-selected terrain
3. wait

### Game version and build number

V0.5.5D (B259)

### Operating system

Windows

### Attachments

[24-02-26_03-32-34_8696.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/14399169/24-02-26_03-32-34_8696.log)

[Curland.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/14399224/Curland.zip)

**Comment by poltime** [comment] 2024-02-27 22:00
It works correctly for me, the problem is with your PC, probably the graphics driver. There is NVIDIA GeForce GTX 1050 Ti in my PC.

![Untitled](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/157929411/41074c0d-90a2-4508-9f71-e7c074c1db8c)

**Comment by redshadow3** [comment] 2024-02-28 01:51
>It works correctly for me, the problem is with your PC, probably the graphics driver. There is NVIDIA GeForce GTX 1050 Ti in my PC.

i dont think its ONLY the graphics driver, if its not terraforming terrain that has been selected for leveling before the save was loaded, then this happens:
![Zrzut ekranu 2024-02-28 024825](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/106045016/6f877b73-9f56-4d61-8be3-3b3ec838c279)
only the terrain that had no blueprint on it, is being properly visualized
removing the blueprints does nothing, it still doesnt update the terrain the blueprints used to be on
of course, this could be an FPS issue but i dont see how that would cause this

**Comment by poltime** [comment] 2024-02-28 02:06
Сheck how it works on another PC.

**Comment by redshadow3** [comment] 2024-02-28 02:22
> Сheck how it works on another PC.

i dont have another one..

**Comment by MaFi-Games** [comment] 2024-04-18 16:42
I can't reproduce it either and there are no issues in the log file. It might be driver related. Closing as not reproducible.

**Closed as not planned by MaFi-Games** 2024-04-18 16:42 UTC
