### ISSUE TITLE
Vehicle overview not correct

### ISSUE THREAD

**Issue by Johnnoq** [MaFi-Games/Captain-of-Industry-issues#522] opened 2022-07-06 23:29 UTC
### Issue description

the vehicle overview has idle pickups while i dont have them anymore.

see attachment

### Expected behavior

to be correct :D

### Game version

v0.4.7c

### Attachments

![error idle vehicles](https://user-images.githubusercontent.com/89051015/177659379-ee9b1da0-1aed-4be8-b371-708e29f40050.png)

**Comment by MaFi-Games** [comment] 2022-07-08 10:07
Duplicate of #524

**Closed** 2022-07-08 10:07 UTC
