### ISSUE TITLE
Game Failed to Initialize

### ISSUE THREAD

**Issue by shaunsters** [MaFi-Games/Captain-of-Industry-issues#495] opened 2022-07-04 01:15 UTC
**Describe the issue**
A clear and concise description of what the issue goes here.

**Expected behavior**
[22-07-03_21-12-41_3455.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9035852/22-07-03_21-12-41_3455.log)

Explain what you expected to happen.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.

**Comment by MaFi-Games** [comment] 2022-07-04 10:09
Ok, in logs I can see the following:
X 01:14:13,274 S1022120 ~Mai: Exception during game initialization.
 ---> NullReferenceException: Object reference not set to an instance of an object
  at Mafi.Unity.Entities.Static.ConstructionCubesFactory.GetCubesCount (Mafi.Core.Entities.Static.IStaticEntity entity)  
  at Mafi.Unity.Entities.Static.EntityConstructionRecord.UpdateStateOnSync ()  
  at Mafi.Unity.Entities.Static.EntityConstructionRecord..ctor (Mafi.Unity.Entities.Static.ConstructionCubesUpdater updater, Mafi.Core.Entities.Static.IStaticEntity entity, Mafi.Unity.Entities.EntityMb entityMb)  
  at Mafi.Unity.Entities.Static.ConstructionCubesUpdater.AddOnSyncIfNeeded (Mafi.Unity.Entities.EntityMb entityMb) [0x0001c]  
  at Mafi.Unity.Entities.EntitiesRenderer.addImmediate (Mafi.Core.Entities.IRenderedEntity entity) [0x0011a]

**Comment by MaFi-Games** [comment] 2022-07-04 10:53
Duplicate of #453

**Comment by MaFi-Games** [comment] 2022-07-04 13:28
We have found the issue but cannot figure out how it happened. Would you please have older log files as well?

**Comment by MaFi-Games** [comment] 2022-07-04 23:48
This has been fixed in `v0.4.7b`, thanks for the report.

**Closed by MaFi-Games** 2022-07-04 23:48 UTC
Labels: bug, high priority
