### ISSUE TITLE
Trucks not able to dump in a dumping zone close to world border

### ISSUE THREAD

**Issue by mcreationshh** [MaFi-Games/Captain-of-Industry-issues#609] opened 2022-07-19 18:59 UTC
### Issue description

Tho, one can make a dumping zone (,which has worked flaswlessy the hole time), trucks refuse to dump close to the (nearly invisble) world border. Map: Curland. Trucks give notice: 'searching for valid terrain designation'

### Expected behavior

trucks continue dumping until map border

### Game version

v.0.4.8

### Attachments

[firsttry26a.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9143945/firsttry26a.zip)

**Comment by ParanoikCZE** [comment] 2022-07-20 00:13
Didn't check the save, but probably a duplicate of #578

**Comment by MaFi-Games** [comment] 2022-08-20 14:08
Duplicate of #578

**Closed** 2022-08-20 14:08 UTC
Labels: duplicate
