### ISSUE TITLE
pathfinding still with issue

### ISSUE THREAD

**Issue by serginhov2** [MaFi-Games/Captain-of-Industry-issues#1101] opened 2023-06-12 13:10 UTC
### Issue description

Hello,

I'm checking the path finder in a late game and the trucks still stuck trying to send resources, maybe it will be good to add a pathfinder check, if the truck cannot send resources they will choose another path to send.

### Reproduction steps

trucks stuck in pathfinding when they cannot send the resource

### Game version and build number

last

### Operating system

Windows

### Attachments

[23-06-03_16-28-autosave-paused.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11723464/23-06-03_16-28-autosave-paused.zip)

**Comment by MaFi-Games** [comment] 2023-06-12 21:31
Could you please clarify which truck and resource you consider stuck in your save file? I didn't see any issue there. Please note that sometimes trucks can get jobs they can't path to, but that is expected to be solved by the player. Because planning the jobs assignments based on their pathability would be extremely expensive on CPU.

**Comment by serginhov2** [comment] 2023-06-12 21:33
In my conception if the truck cannot do the job, it should start another job and don't get stuck, for example, if the truck cannot reach a coal warehouse It should start deploying the coal in another site and not get stuck stopping the logistic.

**Comment by MaFi-Games** [comment] 2023-06-15 13:44
That behavior has other consequences, including performance penalty. Even if we'd decide to dive into this, we track effort like this separately, internally. I'll close this as - working as intended for now as here we go mainly after bugs. But thanks for bringing this up!

**Closed** 2023-06-15 13:44 UTC
Labels: could not reproduce, works as intended
