### ISSUE TITLE
cracking unit recipe bugged output

### ISSUE THREAD

**Issue by KhanTengri** [MaFi-Games/Captain-of-Industry-issues#1016] opened 2023-05-31 18:50 UTC
### Issue description

setting the cracking unit to the recipe naptha+steam -->fuel gas, sour water seems to output fuel gas from both pipe outputs even though one is specifically labeled sour water output. this might only happen if the fuel gas output pipe is full

### Expected behavior

Cracking unit should have dedicated specific unique outputs for this recipe one for fuel gas and one for sour water and should not be pumping out fuel gas into the sour water stream.

### Reproduction steps

Load save (I am using captain of cheats mod but I dont think that's causing the issue here
the cracking units should be right in the save, I have attached flares to each to clean up the fuel gas coming out the sour water output

[fuel problem.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11617875/fuel.problem.zip)

### Game version

Update 1

**Comment by zuff-coi** [comment] 2023-06-03 18:58
I could not reproduce this issue.

**Comment by KhanTengri** [comment] 2023-06-03 19:20
Yeah with the lastest update neither could I.  On Jun 3, 2023, at 11:58 AM, Captain Zuff ***@***.***> wrote:﻿
I could not reproduce this issue.

**Comment by MaFi-Games** [comment] 2023-06-04 20:47
Most likely fixed in one of our previous patches. Thanks!

**Closed by MaFi-Games** 2023-06-04 20:47 UTC
Labels: could not reproduce
