### ISSUE TITLE
Save files disappeared (not lost) on Win11 with Controlled Folder Access

### ISSUE THREAD

**Issue by vmmitev** [MaFi-Games/Captain-of-Industry-issues#225] opened 2022-06-05 21:26 UTC
**Describe the issue**
As mentioned in the title the save files disappeared on my Win11 with Controlled Folder Access (Ransomware Protection). I'm not sure if that's the reason behind the disappearance as I was getting notifications the game needed access to the <User>\Documents\Captain of Industry folder which I eventually gave. The saves were there after I started the game today but then the game requested more general access to the <User>\Documents root which I also allowed. I also see that Steam also needed access (my guess is for the cloud save). ~~Unfortunately it seems I have lost all my progress. Did the game temporarily store the save files somewhere else with less privileged access initially and now that it has full access to the regular folder they're not being found?~~ Edit (after I wrote all the other topics): It looks like all my saves are safe and sound under <SteamLibrary>\steamapps\common\Captain of Industry\Saves

**Expected behavior**
Maybe show an error message if the game has no write access to the default save folder due to system permissions (could be caused by other software as well). Edit: Or load/transfer saves from the steamapps folder, whichever is easier.

**To Reproduce**
1. Activate Controlled Folder Access in Win 11 or block access to the save folder using other means
2. Play the game and do some saves (use Steam cloud save sync)
3. Restart the game and check if the saves are still being discovered
4. Lift the restriction from step 1 during gameplay and do additional saves (Steam might also need to get access to the folder)
5. Restart the game and check if the saves from step 2 and 4 are available

**Additional context**
 - Game version: 0.4.1E

**Attachments**
Since I checked the log files and noticed the D:\Games\SteamLibrary\steamapps\common\Captain of Industry\DLCs folder I checked it out and found that my saves were still stored around the game installation folder. Hooray! I won't upload them as the issue seems to be caused by how the game gracefully changes which save folder to use but it can end up in confusion if you end up doing what I did.

**Comment by MaFi-Games** [comment] 2022-06-05 22:01
This is likely Windows doing some automatic redirection for file access. The game is always accessing `Documents/Captain of Industry` folder for saves.

**Comment by MaFi-Games** [comment] 2022-06-16 23:28
Did you figure out what was the issue? We had other players report that the saves are in steamapps folder, see #252 .

**Comment by vmmitev** [comment] 2022-07-02 09:49
I know what caused it, it was the Win11 setting for Controlled Folder Access (Ransomware Protection). I don't know how the game decides to write into the steamapps folder but given that the game now has a browse savefile folder option maybe it can be updated to switch between both folders in case other people run into this?

**Comment by MaFi-Games** [comment] 2022-11-26 17:44
Duplicate of #896

**Closed by MaFi-Games** 2022-11-26 17:44 UTC
