### ISSUE TITLE
Truck assigned to mine control tower does not dump

### ISSUE THREAD

**Issue by PKHenkel** [MaFi-Games/Captain-of-Industry-issues#123] opened 2022-01-21 02:04 UTC
About the time I discovered medium trucks Some trucks assigned to a mine control tower stopped dumping rocks, in this case, in the dumping zone. The moment the truck gets unassigned it will dump like it is supposed to. There are loose storages for ore and rocks and a loose storage without designation (should be dirt).

Reproduce:
Load the save game
go to to the mine control tower by the iron zone.
The one truck stays confused.

This may be an effect of assigning a loose storage without setting its content.

**Expected behavior**
As there is a loose storage for rocks assigned, they should be transported there or at least they sould be dumped in zone.

**Additional context**
 - Game version: Beta 0.3.10 steam
![grafik](https://user-images.githubusercontent.com/97865455/150450669-a151a8e6-6211-430a-9e5c-00a08c73e3a5.png)

Save game from image above
[truck no dump.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7909709/truck.no.dump.zip)

**Comment by JamieRCHI** [comment] 2022-06-16 02:44
I am getting a similar issue with v0.4.4a.
I have a dump area elsewhere assigned with a tower to mine iron.
A second tower to dump dirt.
The dirt will not be dumped to the area defined to dump by the second tower.
Should the primary tower require the dump icon to be added to allow dumping to the second tower area?
If so that makes no sense to me.
Dump rules should apply only to area of influence of that tower.

Currently, I can only dump from the tower to a loose storage elsewhere. The trucks will not directly dump from one tower to another.

**Comment by JamieRCHI** [comment] 2022-06-25 16:56
Note that this issue is before version 0.4.x released in Early Access.
Quoting from above: "This may be an effect of assigning a loose storage without setting its content."
Based on looking at the above info, I would say this issue should be closed, 'By Design'.

**Comment by MaFi-Games** [comment] 2022-11-24 17:48
Thanks for your report. As this seems to be issue in beta (older version) and it is not clear what is going on here we have to close it.

**Closed by MaFi-Games** 2022-11-24 17:48 UTC
Labels: beta issue
