### ISSUE TITLE
Trucks

### ISSUE THREAD

**Issue by semog756** [MaFi-Games/Captain-of-Industry-issues#622] opened 2022-07-25 14:16 UTC
### Issue description

Hi,
We have problems with trucks.
When I have a lot of trucks, when they go to perform some tasks, they stop for a while and then continue to move and this is constant
this is bad because the trucks take time to perform the tasks

### Expected behavior

That dont stop

### Reproduction steps

I dont know

### Game version

v0.4.8

### Attachments

Don have

**Comment by zuff-coi** [comment] 2022-07-25 18:37
Duplicate of #364

**Closed by zuff-coi** 2022-07-25 18:37 UTC
Labels: duplicate

**Comment by zuff-coi** [comment] 2022-07-29 14:54
We [released an update on the experimental branch](https://steamcommunity.com/games/1594320/announcements/detail/3397421255147457180) which has fixes aimed at this issue. If you could please try it out and let us know if your issue is resolved that would be great!
