### ISSUE TITLE
Crashes since big update

### ISSUE THREAD

**Issue by Dasmail2000** [MaFi-Games/Captain-of-Industry-issues#1068] opened 2023-06-07 03:08 UTC
### Issue description

Game is great - worked like a champ with previous version. Since the 'big update', it randomly crashed every 30 minutes or so....sometime longer, sometimes sooner. I have not been able to pinpoint what actions cause it though.

### Expected behavior

Umm..expected it not to crash ;)

### Reproduction steps

Just load game and play. Saved game or new game does not matter....after 30 minutes or so, it crashes.

### Game version

v0.5.1

### Attachments

[Three.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11672073/Three.zip)
[Player-prev.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11672075/Player-prev.log)
[Player.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11672076/Player.log)
[Crash_2023-06-07_023858641.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11672092/Crash_2023-06-07_023858641.zip)

**Comment by MaFi-Games** [comment] 2023-06-07 15:09
Duplicate of  #1051

**Comment by MaFi-Games** [comment] 2023-06-07 15:10
Duplicate of #1051

**Closed by MaFi-Games** 2023-06-07 15:10 UTC
