### ISSUE TITLE
Blast Furnace mk2 bugs

### ISSUE THREAD

**Issue by NIRE005** [MaFi-Games/Captain-of-Industry-issues#1133] opened 2023-06-18 18:25 UTC
### Issue description

Is it just a problem on my game or does everybody see instead of an blast furnace a purple and white squared building?

### Reproduction steps

1. load in any save. 
2. build a blast furnace mk2 and if its not a personal issue it should show up with purple and white squares instead of the actual furnace

### Game version and build number

v0.5.2A (B215)

### Operating system

Windows

### Attachments

![20230618202347_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/136998411/18b7a60e-673d-4af5-a4aa-8c0dcd2589d7)
![20230618202337_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/136998411/a550c0f2-9695-437d-bbd2-bb1e52fd992e)

**Comment by MaFi-Games** [comment] 2023-06-18 20:08
This seems to be some issue on your side. You can request Steam app to verify integrity of the game file on your local system. Also make sure there are no mods redefining these entities and removing their graphics.

**Comment by MaFi-Games** [comment] 2023-08-04 14:54
Closing as not reproducible.

**Closed by MaFi-Games** 2023-08-04 14:54 UTC
Labels: potential issue on user side
