### ISSUE TITLE
Suggestion: Add Mute button at top left to mute alerts. (Low Priority)

### ISSUE THREAD

**Issue by JamieRCHI** [MaFi-Games/Captain-of-Industry-issues#370] opened 2022-06-18 00:58 UTC
This should mute both alerts on the left and errors on the right.
Currently does nothing.

Another option that would be nice is to have an additional mute on the left of the screen that mutes the alerts on the left side, the right existing mute button should only effect the right side with the added option of changing when it makes noise.
Like beep always, beep only with errors, beep disabled.

**Comment by MaFi-Games** [comment] 2022-06-21 11:42
It mutes events for me just fine. It does not mute the notifications on the left side but that is working as intended.

**Comment by JamieRCHI** [comment] 2022-06-21 16:04
Ok. I understand that this is By Design at this point. I wil edit the title to change this into a Suggestion.

**Comment by MaFi-Games** [comment] 2022-11-25 17:10
Alerts that were displayed on the left side are being removed in the new version

**Comment by zuff-coi** [comment] 2022-12-23 18:12
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.

**Comment by zuff-coi** [comment] 2022-12-23 18:13
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.

**Comment by zuff-coi** [comment] 2022-12-23 18:13
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.

**Closed by zuff-coi** 2022-12-23 18:13 UTC
Labels: fixed in v0.4.13
