### ISSUE TITLE
Unity spam

### ISSUE THREAD

**Issue by GuardianDragonlord** [MaFi-Games/Captain-of-Industry-issues#1073] opened 2023-06-07 19:58 UTC
**The issue**
upgrade multiple buildings with unity clicking the button maybe too many times

**Expected behavior**
I was expecting the buildings to be build and constructed quickly without any hiccups

**To Reproduce**
I started to put a ramp down then attached a belt to connect one storage to another then started upgrading a bunch of storages for my copper production and then the crash

**Additional context**
1 V0.5.1B

**Attachments**

**Comment by MaFi-Games** [comment] 2023-06-08 10:59
Sorry, I'm not sure I follow, what is supposed to be the issue here?

**Comment by MaFi-Games** [comment] 2023-08-06 18:28
Duplicate of #1067

**Closed by MaFi-Games** 2023-08-06 18:28 UTC
