### ISSUE TITLE
Labs at half production

### ISSUE THREAD

**Issue by Scott888888** [MaFi-Games/Captain-of-Industry-issues#605] opened 2022-07-18 22:27 UTC
**The issue**
The electric assembly units are only producing half the lab research they're supposed to:

- White is supposed to be produced at 8; only 4 coming out
- Yellow & red labs should be 4; only 2 at a time

This happened with the mechanical parts a few days ago but that was fixed.

**Expected behavior**
Should be doing what it says it should.

**To Reproduce**
Describe steps to reproduce the issue here, for example:
It's happening all the time

**Additional context**
 - Game version: 0.4.8

**Comment by Scott888888** [comment] 2022-07-19 01:59
So I looked at it more closely and it's just a visual thing. Half as many tokens are coming out of each assembler but, once they get to the next step, they show up as the proper input.

**Comment by ParanoikCZE** [comment] 2022-07-19 08:24
That's because you are probably using T2 belt. They are stacking items together. Same with T3.

**Comment by zuff-coi** [comment] 2022-07-20 14:54
Duplicate of #531

**Comment by Scott888888** [comment] 2022-07-22 12:42
You're right. I am. Didn't realize that.
Thanks,
Scott

**Closed** 2022-07-23 12:29 UTC
Labels: duplicate
