### ISSUE TITLE
Frequent Crashing

### ISSUE THREAD

**Issue by rarrisgithub** [MaFi-Games/Captain-of-Industry-issues#447] opened 2022-06-28 15:36 UTC
Describe the issue:

Frequent crashing, needing crtl+alt+del end the process

Expected behavior

Not crash!

To Reproduce:

Cannot reliably reproduce or find a pattern, can happen after 10 mins, not more than 30 mins before a crash. 

Additional context

Game version: 0.4.6
Graphics card: NVIDIA RTX A4000 
Windows 11
Player and Player-prev file log file attached
[Player-prev.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9002518/Player-prev.zip)

**Comment by MaFi-Games** [comment] 2022-06-28 15:55
Can you please attach logs from C:/Users/Dickie/AppData/Local/Temp/Mafi Games/Captain of Industry/Crashes ?

**Comment by rarrisgithub** [comment] 2022-06-28 15:58
> Can you please attach logs from C:/Users/Dickie/AppData/Local/Temp/Mafi Games/Captain of Industry/Crashes ?

Of course, thank you, attached.
[Crash_2022-06-28_151233775.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9002689/Crash_2022-06-28_151233775.zip)

**Comment by rarrisgithub** [comment] 2022-07-06 13:28
Hi, I'm still getting frequent crashes - do the logs reveal any potetial causes that I could try fixing?
Thank you

**Comment by MaFi-Games** [comment] 2022-07-08 20:59
We are not sure why is this happening. The crash seems to be coming from the Unity engine. Could you please also share us logs  from  %userprofile%\Documents\Captain Of Industry\Logs ?

**Comment by rarrisgithub** [comment] 2022-07-09 11:38
Sure, please see attached - crashed a few mins ago. 
[Logs.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9076403/Logs.zip)

**Comment by rarrisgithub** [comment] 2022-07-13 14:50
Hi, did the logs help at all? Let me know if you need anything further. Thanks, I appreciate your help!

**Comment by MaFi-Games** [comment] 2022-08-22 21:46
Hey, thanks for the logs but unfortunately no information there. We did upgrade Unity version in our last patch though. Did it help to solve your issue by any chance?

**Comment by MaFi-Games** [comment] 2022-11-25 17:52
Closing as we cannot reproduce and there is no new information

**Closed by MaFi-Games** 2022-11-25 17:52 UTC
Labels: needs investigation
