### ISSUE TITLE
High pressure turbine cant flip 

### ISSUE THREAD

**Issue by Killerk83** [MaFi-Games/Captain-of-Industry-issues#26] opened 2021-09-29 03:40 UTC
**Describe the issue**
A clear and concise description of what the issue goes here.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Expected behavior**

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]

**Attachments**
If applicable, add save files (zipped), screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%/Documents/CaptainOfIndustry/`). You might need to ZIP the attached files.

**Comment by MaFi-Games** [comment] 2021-10-01 06:15
This is actually by design, but we are getting many reports about this we might need to add this functionality. It is not trivial to fix due to directionality of the shaft (all machines on the shaft need to rotate the same direction). I will keep this open until we have further info on this. Thanks for reporting!

**Comment by BVHagop** [comment] 2022-06-13 16:33
Just wanted to bump this as add I would like a see the whole power train get a flipped version.

**Comment by MaFi-Games** [comment] 2023-06-20 19:18
Option to flip turbines was introduced in one of our previous updates. So closing as completed!

**Closed by MaFi-Games** 2023-06-20 19:18 UTC
Labels: feature request, works as intended, beta issue
