### ISSUE TITLE
Trucks stalling

### ISSUE THREAD

**Issue by knmh84** [MaFi-Games/Captain-of-Industry-issues#367] opened 2022-06-17 21:20 UTC
the trucks wont move even if destination is near and trucks are loaded and there are not another queue
[22-06-17_20-11-58_8328-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8931311/22-06-17_20-11-58_8328-autosave.zip)

**Comment by knmh84** [comment] 2022-06-19 15:34
here is an early save of same island... as soon as go and start digging on other end all my trucks start stalling does not matter if i have 90 trucks or 200 trucks the whole system seem to just crash ... attached is another save file .. saved as soon as it started
[Trucks stalling issue.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8935834/Trucks.stalling.issue.zip)

**Comment by Berkajerk** [comment] 2022-06-19 20:17
Two saves and a screenshot where I have a priority P1 belt and storage being built but the the full storage of yellow parts aren't being delivered even though the trucks are at "Stable" and there are 2 trucks specifically assigned to the storage. I can use Unity to Quick Deliver but trucks simply refuse to deliver from the storage even when it's marked as Export and Import allowed.

Love the game keep up the hard work!!!!

[trucks not taking up priority jobs.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8936317/trucks.not.taking.up.priority.jobs.zip)

**Comment by zuff-coi** [comment] 2022-07-12 16:59
Duplicate of #364

**Closed by zuff-coi** 2022-07-12 16:59 UTC

**Comment by zuff-coi** [comment] 2022-07-29 14:51
We [released an update on the experimental branch](https://steamcommunity.com/games/1594320/announcements/detail/4972554042131344663) which has fixes aimed at this issue. If you could please try it out and let us know if your issue is resolved that would be great!

**Comment by knmh84** [comment] 2022-07-29 14:56
Thanks that works flawless
