### ISSUE TITLE
Game Scrolling Error on Map Screen

### ISSUE THREAD

**Issue by Siagrim73** [MaFi-Games/Captain-of-Industry-issues#5] opened 2021-09-16 17:52 UTC
**Describe the issue**
When i start a new game the world is always moving in the upper left corner.
In the main menu everything is working fine. 
Even when i click the mousweehl to move the camera, it goes always scrolls in the upper left corner.

**To Reproduce**
1. disconnected every device from USB 3.0 Hub except mouse (G502 Logitech) and keyboard (Corsair K55).
2. Closed any program of the joysticks, TM16000, VPC Delta, Tobii5, 2 midi Keyboards, Webcam
3. Tried every monitor to play the game in most any resolution. (Benq 28 4K,HDR, PEAQ TFT 1980)
4. Deinstallation of the mouse driver and restart of the pc
5. connected a Corsair Gaming Mouse (Glaive PRO). Same issue.
6. Used programs: NVIDIA Driver, UMC Asio Driver, Avira Free, Logitech GHub, MSI Afterburner, Tobii5 Eye Software, Corsair Wireless Headset, iCUE, RivaTuner, VoiceMeeter Banana (For Audio Routing), AKAI Midi Keyboard, Yamaha P10 E-Piano (USBtoMidi)

**Expected behavior**
The automatic scrolling in the upper left corner should stop.

**Additional context**
 - Game version: 0.2.0A

**Attachments**
If applicable, add save files, screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%/Documents/CaptainOfIndustry/`)
[21-09-16_17-45-02_8001.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7179939/21-09-16_17-45-02_8001.log)
[21-09-16_17-44-16_4641.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7179940/21-09-16_17-44-16_4641.log)
[21-09-16_17-43-27_6975.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7179941/21-09-16_17-43-27_6975.log)
[21-09-16_19-43-59_4262.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7179942/21-09-16_19-43-59_4262.log)
[21-09-16_19-26-04_2256.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7179943/21-09-16_19-26-04_2256.log)
[21-09-16_18-25-45_5657.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7179944/21-09-16_18-25-45_5657.log)
[21-09-16_18-21-34_7533.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7179945/21-09-16_18-21-34_7533.log)
[21-09-16_17-57-01_6150.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7179946/21-09-16_17-57-01_6150.log)
[21-09-16_17-51-25_8348.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7179947/21-09-16_17-51-25_8348.log)
[21-09-16_17-46-06_7361.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7179948/21-09-16_17-46-06_7361.log)

**Comment by Str3amR** [comment] 2021-09-16 21:30
Probably related to https://github.com/MaFi-Games/Captain-of-Industry-issues/issues/1

**Comment by Siagrim73** [comment] 2021-09-16 22:23
i have disconnected every joystick or game controller

**Comment by Siagrim73** [comment] 2021-09-16 22:54
I found it out.
The program vJoy caused the problem and JostickCurves, too.
Everyone who is using these programs should deinstall it.
Even if no Joystick is attached, the program simulates the input and is causing the problem with the scrolling error.

**Comment by MaFi-Games** [comment] 2021-09-16 23:26
Yeah, this could be caused by "virtual" joysticks. This has been fixed once, but it returned. I will see how to avoid this.

**Comment by MaFi-Games** [comment] 2021-09-16 23:26
Duplicate of #1

**Closed** 2021-09-16 23:28 UTC
