### ISSUE TITLE
game locked up

### ISSUE THREAD

**Issue by GuardianDragonlord** [MaFi-Games/Captain-of-Industry-issues#1098] opened 2023-06-12 03:28 UTC
### Issue description

As soon as I finished placing down buildings and constructing a few things, the game locked up and didn't bother crashing. It was simply Frozen and non-responsive had to force close it.

### Reproduction steps

I rearranged my dump locations, constructed a ramp, put some conveyor belts over, and then crashed.

### Game version and build number

v0.5.1B (B206)

### Operating system

Windows

### Attachments

[23-06-11_20-09-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11717233/23-06-11_20-09-autosave.zip)

**Comment by MaFi-Games** [comment] 2023-06-12 21:07
Can you please provide logs? This seems like Unit / hardware issue. Save file won't help here much.

**Comment by GuardianDragonlord** [comment] 2023-06-14 01:21
The game is crashing based on falling Rock cliffs when they are 20 layers tall, and it comes crashing down; it seems to be causing the issue, but that is only a guess.
[23-06-13_17-53-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11740605/23-06-13_17-53-autosave.zip)
[23-06-13_16-06-56_0503.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11740606/23-06-13_16-06-56_0503.log)
[Player-prev.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11740607/Player-prev.log)

**Comment by MaFi-Games** [comment] 2023-08-06 18:28
Duplicate of #1067

**Closed by MaFi-Games** 2023-08-06 18:28 UTC
Labels: need logs
