### ISSUE TITLE
Its dark i cant see.

### ISSUE THREAD

**Issue by Sharknadohehe** [MaFi-Games/Captain-of-Industry-issues#914] opened 2022-12-23 23:31 UTC
### Issue description

So with the newest update i found a bug that crashes my game every time. So i unlocked the transformer for my ppl but every time i place it i get the white boxs that has the Captain of Industry logo on it and my game crashes. thankfully autosave is on but it dark out here my ppl cant see when they wake up at 4 am to go to work and no coffee OMG there so slow now haha.

### Expected behavior

just expected it to place. i did this 2 times till i figured out what it was.

### Reproduction steps

1. click on transformer
2. place transformer
3. disapointment has arrived
4. game crashed

### Game version

v0.4.13

### Attachments

https://1drv.ms/u/s!ArMq3s42zGYsgQUB0hvAyNvBGQXi?e=rXHZpr

**Comment by MaFi-Games** [comment] 2022-12-24 00:58
Thanks for the report but I was unable to reproduce the problem, transformed places and builds for me just fine.

Whenever you get the crash again, can you attach logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`?

**Comment by MaFi-Games** [comment] 2023-07-28 10:01
Closing as we can't reproduce.

**Closed by MaFi-Games** 2023-07-28 10:01 UTC
Labels: could not reproduce, high priority
