### ISSUE TITLE
"GetCubesCount" exception on trying to load save files

### ISSUE THREAD

**Issue by windock** [MaFi-Games/Captain-of-Industry-issues#505] opened 2022-07-04 17:33 UTC
**Describe the issue**
Loading a save file. I get an exception "GetCubesCount", see screenshot

**Expected behavior**
Save is loaded

**To Reproduce**
1. Load attached save '...'

**Additional context**
 - Game version: 0.4.7A

**Attachments**
![exception](https://user-images.githubusercontent.com/79237/177197793-12173bf2-8c93-4ce4-acd1-85a9f7e7bba7.png)
[22-07-04_20-17-42_4963.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9041257/22-07-04_20-17-42_4963.log)
[save_22-07-03_18-51-21.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9041265/save_22-07-03_18-51-21.zip)

Here is the last save file that can be loaded. All the consequent auto save files (I presume created after the latest update) get this problem. Also, I cannot just run the game for a few seconds, and get a broken save file. Manual save file right after loading can be loaded 
[save_22-07-02_23-37-24.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9041284/save_22-07-02_23-37-24.zip)

**Comment by MaFi-Games** [comment] 2022-07-04 18:36
Thanks for your report. It seems to appear when you remove the coal storage near the power plant. Could you please share some specific steps you have done there?

**Comment by MaFi-Games** [comment] 2022-07-04 18:37
Duplicate of #453

**Comment by windock** [comment] 2022-07-04 18:44
My coal was running out, and there were electricity shortages. A few steps I remember doing is
- add conveyor belts for coal that would go around the balancer since it did not get electricity to run
- removed extra storage near the coal plant, as it was taking all the coal, and iron/copper smelting did not get any
- added an additional balancer near that coal plant so that coal goes to first coal plant until 100% load, and then to the next one

**Comment by windock** [comment] 2022-07-04 18:47
Also, the issue is repeatable. Yesterday, I had the same issue, loaded the same file, played for the evening, and today I could not load all new save files again.

**Comment by MaFi-Games** [comment] 2022-07-04 23:47
This has been fixed in `v0.4.7b`, thanks for the report.

**Closed by MaFi-Games** 2022-07-04 23:47 UTC

**Comment by windock** [comment] 2022-07-05 16:27
I confirm, the issue is fixed. Thank you!
