### ISSUE TITLE
[Dublicate] 459 Belt Sorter throughput is missing Information

### ISSUE THREAD

**Issue by paulpascher** [MaFi-Games/Captain-of-Industry-issues#479] opened 2022-07-02 10:46 UTC
Sorry Duplicate with:
https://github.com/MaFi-Games/Captain-of-Industry-issues/issues/459
And i don't know how to Delete my post

**Describe the issue**
U-Shape Sorter / all sorters don't show throughput! 
 
**Expected behavior**
they should show throughput in tooltip or be as fast as connected belts or even faster. They are a bottleneck with no information
it requires a lot of testing to realize how many parallel sorters you need to accept a full T3 belt

**To Reproduce**
place some U-Shape-Sorters and watch them Sort ^^

**Additional context**
 - Game version: [EARLY ACCESS 0.4.6]

**Attachments**
-,-

**Comment by MaFi-Games** [comment] 2022-07-03 04:47
Duplicate of #459

**Closed by MaFi-Games** 2022-07-03 04:47 UTC
