### ISSUE TITLE
Serious issue with pipe balancers and their priority I/O

### ISSUE THREAD

**Issue by MainTango** [MaFi-Games/Captain-of-Industry-issues#319] opened 2022-06-12 15:56 UTC
**Describe the issue**
When inputting N2 into a pipe balancer through a pipe that is only 1 tile long, the balancer sends some into non-priority outputs, even though the priority output should easily handle the entire input.
Note: The priority output is NOT full.

**Expected behavior**
100% of the input should be routed to the priority output until it's full.

**To Reproduce**
Check attached screenshot.

**Additional context**
 - Game version: EA v0.4.3

**Attachments**
Screenshot
![2022-06-12_16-52-13](https://user-images.githubusercontent.com/10602027/173241847-b8b73310-fac0-4d60-a0be-8ac2efda2fdb.jpg)

**Comment by LottieVixen** [comment] 2022-06-12 16:08
seems to be a duplicate or related to #298

**Comment by MaFi-Games** [comment] 2022-07-03 04:45
Duplicate of #298

**Comment by MaFi-Games** [comment] 2022-07-03 04:45
Thanks for the reports, this has been fixed in v0.4.7!

**Closed by MaFi-Games** 2022-07-03 04:45 UTC
