### ISSUE TITLE
UI Shrinking in certain windows

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#443] opened 2022-06-28 03:35 UTC
![image](https://user-images.githubusercontent.com/108291414/176086395-285b8d92-1723-4d54-a742-2e6abb7fac27.png)

From sonny40732 on discord:
"seems like there is an intermittent bug with the menu ui, where sometimes is squishes the section down quite small. But I walked away from my desk for a minute and it fixed itself, but I managed to snatch a screenshot"

Other notes:
"I've noticed that too. Mostly in the research menu"
"ui scale is 100% and res is 1920x1080. And it seems to be entirely intermittent, if it happens all i have to do is close the research menu and open it back up and it's fixed, and i cannot find any trigger that causes it"

Version: v0.4.6

**Comment by MaFi-Games** [comment] 2022-06-28 07:02
Can we try to collect more data? E.g. what is the resolution & ui scale?

**Comment by zuff-coi** [comment] 2022-06-28 14:58
> sonny40732

I've contacted them on discord to try to get more information. Will update the OP when I have more.

**Comment by zuff-coi** [comment] 2022-06-28 15:18
> Can we try to collect more data? E.g. what is the resolution & ui scale?

Additional notes added, 1920x1080, 100% scale

**Comment by MaFi-Games** [comment] 2023-08-04 17:32
Duplicate of #1176

**Closed by MaFi-Games** 2023-08-04 17:32 UTC
