### ISSUE TITLE
Tier 3 vehicles will use the main cargo dock when Advanced Logistics is enabled 

### ISSUE THREAD

**Issue by SwiftNicholas** [MaFi-Games/Captain-of-Industry-issues#328] opened 2022-06-13 05:12 UTC
Must have advanced logistics enabled and the originating container have dump paths, if the dump paths can't be reached or are out of postions to dump then the T3 truck will force the waste (in my case) into the dock.

**Comment by MaFi-Games** [comment] 2022-11-26 22:36
Duplicate of #287

**Closed by MaFi-Games** 2022-11-26 22:36 UTC
