### ISSUE TITLE
Trucks driving themselves stuck

### ISSUE THREAD

**Issue by iProfessore** [MaFi-Games/Captain-of-Industry-issues#1251] opened 2023-08-31 14:16 UTC
### Issue description

This is hard to reproduce because it is dependant on what a paerticular truck is doing at the time.
A U shape of buildings has been built blocking vehicles on three sides.
A conveyor belt is placed between the ends at level 0 or 1 closing off the square.
While the belt is in the blue building phase a truck will drive straight through the belt into the square to collect or deliver. Once it has done it's thing it will say "I can't get out". 
It should not have driven straight through the blue belt to start with, A player cannot know a truck is coming and wait before building the belt. There should be some intelligence stopping the truck from entering the square.
The only option is to delete the belt, force the truck out of the square (it does not realise it can now get out) and then build the belt all over again.

### Reproduction steps

Create as issue description
it has happened like this over several versions

### Game version and build number

v0.5.4g

### Operating system

Windows

**Comment by MaFi-Games** [comment] 2023-08-31 14:29
Duplicate of #338

**Closed as not planned by MaFi-Games** 2023-08-31 14:29 UTC
