### ISSUE TITLE
Turck Train

### ISSUE THREAD

**Issue by Zacke222** [MaFi-Games/Captain-of-Industry-issues#572] opened 2022-07-14 20:00 UTC
### Issue description

Onnly one truck at a time will go to Storage.
If you have 10 iron trucks delivering to 3 combined storage IV.
then the trucks will only try to put the iron into one of the storage IV and ingore the othere 2.
Evry time a truck arrives the rest of the trucks that are inbound to deliver stops.
So you migth have 10-20 trucks standing all over the map beckous evry time one is unloding the otheres stop where they are.
If you want to build a iron dump it works but not with any kind of storage white more then 1 tryck delivering.

### Expected behavior

Please make it so that more then 1 truck at a time can unload at a big storage or that they at least try the storage that are beside it to get a better flow of resorces.

### Reproduction steps

1 load save
2 watch the truck delivering ores to the storage
3 have a nice day =)w

### Game version

v0.4.7D

### Attachments

[0000002.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9114947/0000002.zip)

**Comment by ParanoikCZE** [comment] 2022-07-14 21:09
Another duplicate of #364

Btw you should use some grammar check software, like Grammarly. This report hurts my eyes.

**Closed** 2022-07-15 05:40 UTC

**Comment by zuff-coi** [comment] 2022-07-29 14:54
We [released an update on the experimental branch](https://steamcommunity.com/games/1594320/announcements/detail/3397421255147457180) which has fixes aimed at this issue. If you could please try it out and let us know if your issue is resolved that would be great!
