### ISSUE TITLE
Escape key during Cut erases entire planning buffer

### ISSUE THREAD

**Issue by omegahacker** [MaFi-Games/Captain-of-Industry-issues#724] opened 2022-08-17 04:56 UTC
### Issue description

Twice now after building a complex factory in planning mode and then using cut to move it around afterward, I have inadvertently hit the Escape key. Both times the entire factory simply vanishes into thin air with no possible recovery.

### Expected behavior

Hitting Escape while planning-mode objects are in the Cut buffer should return those objects to their original location.

### Reproduction steps

- Create factory structure in planning mode
- Cut the factory into the buffer and move it around, but do not place it back down
- Hit the Escape key
- Watch hard work vanish

### Game version

v0.4.10

**Comment by MaFi-Games** [comment] 2022-08-20 12:56
This works as intended.  In several other games Esc will discard the content that was cut as well. It can actually be useful. What you might need is Ctrl + z in this case. That is something on our radar but we track it separately. So I will close this one.

**Closed by MaFi-Games** 2022-08-20 12:56 UTC
Labels: works as intended
