### ISSUE TITLE
Large Tree harvester UI disappears when switching to the vehicle for the first time.

### ISSUE THREAD

**Issue by Dagonesti** [MaFi-Games/Captain-of-Industry-issues#894] opened 2022-11-20 23:47 UTC
### Issue description

Created my first large tree harvester and went to assign a truck and the UI would not appear.  The only way to fix is to save and close the game and then relaunch the game.  This is the third occurrence of this bug for me.  It is slightly annoying but I love this game.

### Expected behavior

I expected the UI to show to allow me to assign a truck to it. 

### Reproduction steps

1. Create a large tree harvester.
2. As it is moving, click on the harvester and the UI should appear.

### Game version

V4.12e

**Comment by MaFi-Games** [comment] 2022-11-22 22:10
Duplicate of #877

**Closed** 2022-11-22 22:11 UTC
