### ISSUE TITLE
Some blueprints not saved

### ISSUE THREAD

**Issue by tippyc2** [MaFi-Games/Captain-of-Industry-issues#962] opened 2023-02-11 02:40 UTC
### Issue description

The first blueprints i saved were in an old save.  I made 2 folders and saved a few blueprints into one of them.  Those two folders and the blueprints in them were saved.
I then went into my most recent save (without closing/restarting the game) and tried to make 4 or 5 new folders and save more blueprints to them, and those ones didnt get saved.  i also re-organized a couple blueprints from the old save into a new folder.  I then had to go do something else, and closed the game.

When i loaded back in, i found that most of the blueprints i tried to save were lost.  The blueprints that i made in the old save were there, but the ones i saved in the recent save were lost.  There were also a couple blueprints from the old save that i re-filed into a new folder, and those were also lost.

I did a bit of poking around and testing to see if i could reproduce the issue.  Poking around in the recent save, I determined that if i save new blueprints to one of those two original folders, they seem to get saved.  I can see file size change on the blueprints.data file, and they're there after reloading the save.  But if i try to save any blueprints outside the folders, or make new folders, those don't get saved.  I can see them on the in-game UI, but the blueprints file size doesnt change, and they're gone if i reload

Going back to the old save again, i was successfully able to make and save new blueprints, bot outside folders and in new folders.  There was a different bit of bugginess that i noticed here though, the blueprints i saved outside the folders didnt appear in the UI, however after reloading the save, they did appear where i had saved them.

Finally, i loaded back into the recent save, and now I'm able to save blueprints and make new folders without any problems.  

### Expected behavior

blueprints should be saved

### Reproduction steps

see description

### Game version

0.4.14 (152)

### Attachments

[newest save temp.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/10712374/newest.save.temp.zip)
[old save temp.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/10712376/old.save.temp.zip)
[logs.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/10712378/logs.zip)
[blueprints.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/10712380/blueprints.zip)

**Comment by zuff-coi** [comment] 2023-02-11 17:54
Thanks for reporting. We believe to have found the cause of losing blueprints and an hotfix should be out soon to resolve the issue.

**Comment by MaFi-Games** [comment] 2023-02-11 18:05
This has been fixed in `v0.4.14a`, thanks for the report!

**Closed by MaFi-Games** 2023-02-11 18:05 UTC
