### ISSUE TITLE
Vehicle Stuck in Greenhouse/Can't be selected

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#645] opened 2022-07-30 18:48 UTC
### Issue description

From Varenvel on the steam forums: https://steamcommunity.com/app/1594320/discussions/2/3463849349647727350/

So i got tree harvester who is stuck below building/inside building , it refuses to move or do anything

i cant click it because building is in way , when i click trucks assigned and then excavator it just moves camera to it(obviously cant click it)

when i try logistics tab and click excavator there (also clicking it there moves camera , not selects the vehicle itself)

so how i get it unstuck without tearing down expensive building

and could i get feature that "clicking" vehicle from logistics or assigned menu would "actually select it too"

### Expected behavior

Be able to select vehicle stuck in building

### Game version

v0.4.8

### Attachments

Screenshot: ![image](https://user-images.githubusercontent.com/108291414/181937402-b335cc5f-8aa6-4351-8113-50e5dfc152b3.png)
Save game: [55.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9227118/55.zip)

**Comment by 0xE1** [comment] 2022-08-27 13:15
Encountered exactly this issue with first tier farm shortly after starting a new game, I forgot to assign a truck to that tree harverster, so it won't move since it already has tree even if I remove tree cutting area and put new one somewhere else
![image](https://user-images.githubusercontent.com/2356882/187031829-a60377a9-7b97-4ff8-b895-8d12eec1fe3b.png)

**Comment by MaFi-Games** [comment] 2022-11-26 17:22
Duplicate of #339

**Closed by MaFi-Games** 2022-11-26 17:22 UTC
Labels: bad behavior
