### ISSUE TITLE
Captain of Industry Crashes Computer

### ISSUE THREAD

**Issue by ArcoDev5332** [MaFi-Games/Captain-of-Industry-issues#1272] opened 2023-09-11 22:54 UTC
### Issue description

When playing captain of industry, my computer has crashed repeatedly. This does not occur with other games. The computer will completely lock up but audio will continue playing.  Video Drivers are up to date. Windows is up to date. Game is up to date. CPU is not overheating. GPU is not overheating. No BSOD logs are generated or any errors in Windows Event System Logs

### Reproduction steps

1. Load ANY save. Has occurred on multiple saves, does not occur in the same place. I cannot find something to cause it to trigger. 
2. Crashes. CTRL ALT Delete does not respond, mouse does not move. Only a hard reboot of computer. 

### Game version and build number

v0.5.5 (B246)

### Operating system

Windows

### Attachments

[23-09-11_17-12-39_8737.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/12580890/23-09-11_17-12-39_8737.log)
[Player.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/12580896/Player.log)

For Crashes, the folder Mafi Games does not exist inside the AppData/Local/Temp directory.

**Comment by MaFi-Games** [comment] 2023-09-18 12:58
If your computer crashes, it is most likely due to hardware or drive issue. Game should not be able to crash your OS. You might want to check the event log for more information on why it crashed: https://www.howtogeek.com/123646/htg-explains-what-the-windows-event-viewer-is-and-how-you-can-use-it/

**Comment by ArcoDev5332** [comment] 2023-09-18 13:01
Hello, I already checked this and noted it in the original report. The
Windows event logs show no crashes, BSODs, or other errors that would
indicate the system has encountered a fatal error.

**Comment by MaFi-Games** [comment] 2024-04-18 17:09
Closing as computer crash can't really be caused by the game.

**Closed as not planned by MaFi-Games** 2024-04-18 17:09 UTC
Labels: potential issue on user side
