### ISSUE TITLE
Trucks drive through things and buildings.

### ISSUE THREAD

**Issue by WakingMoon** [MaFi-Games/Captain-of-Industry-issues#1247] opened 2023-08-29 18:31 UTC
### Issue description

![Skærmbillede 2023-08-29 195747](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/140973349/5c0d7c0f-6d76-47bb-8e2b-710c4bd176dc)
![Skærmbillede 2023-08-29 200115](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/140973349/e0b9918d-890a-41a4-b786-b3884396fe62)

### Reproduction steps

The trucks do it all the time.

### Game version and build number

v0.5.4g b244

### Operating system

Windows

### Attachments

[error truck.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/12468069/error.truck.zip)

**Comment by MaFi-Games** [comment] 2023-08-30 10:21
Duplicate of #338

**Closed as not planned by MaFi-Games** 2023-08-30 10:21 UTC
