### ISSUE TITLE
Pipe Collapsed on Direction Switch

### ISSUE THREAD

**Issue by Frankdcoockle1** [MaFi-Games/Captain-of-Industry-issues#660] opened 2022-08-01 18:00 UTC
### Issue description

I wanted to empty my fuel gas tank. it was connected to a pipe balancer in the back (near input slot). I toggled the pipe direction and boom, it exploded

### Expected behavior

i know it was a mistake to reverse direction of the pipe from input to balancer. i would expect it not to work not to explode....LOL. i also uploaded a screenshot of the explosion

### Reproduction steps

The fuel tank is near the power plants, beside the water desalinators. I realized i couldn't run boilers on fuel gas as they consume too much so i wanted to reverse the fuel and use it somewhere else.  So i reversed direction of the pipes. I also attached a pipe from the fron of the tank to the back pipe that was going into the input. As soon as I hit reverse direction the balancer exploded and then there was a mount of dirt on top of where it used to be, so i couldn't even rebuild. I also attached a screenshot of the aftermath.

### Game version

v0.4.8

### Attachments

![image](https://user-images.githubusercontent.com/110418562/182212317-99a3a831-400f-43c6-a2e7-58fae495154f.png)
![image](https://user-images.githubusercontent.com/110418562/182212347-f9377fe7-a6ba-4d3a-8a87-9b37779c26f8.png)
[Uploading 22-08-01_13-01-autosave.zip…]()

**Comment by Frankdcoockle1** [comment] 2022-08-01 18:01
[22-08-01_13-01-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9236119/22-08-01_13-01-autosave.zip)

**Comment by zuff-coi** [comment] 2022-08-01 18:20
Could be a duplicate of #599

**Comment by zuff-coi** [comment] 2022-08-02 20:56
Could not reproduce in v0.4.9c (experimental)

**Closed by zuff-coi** 2022-08-02 20:56 UTC
Labels: triage
